/**
 * @file Test__Qwen2FP32Parity.cpp
 * @brief End-to-end FP32 parity tests for Qwen2Pipeline against PyTorch reference
 * @author David Sanftenberg
 * @date 2025-11-06
 *
 * Validates Qwen2Pipeline FP32 correctness by comparing against PyTorch ground truth.
 *
 * Test Strategy:
 * - Load PyTorch snapshots generated by generate_qwen2_pipeline_snapshots.py
 * - Run Qwen2Pipeline with same input tokens
 * - Compare intermediate activations stage-by-stage
 * - Tolerance: rel_l2 < 1e-4 for FP32 vs FP32
 *
 * Captured Stages (per layer):
 * - EMBEDDING: Token embeddings
 * - ATTENTION_NORM, Q_PROJECTION, K_PROJECTION, V_PROJECTION
 * - Q_ROPE, K_ROPE, ATTENTION_SCORES, ATTENTION_SOFTMAX
 * - ATTENTION_CONTEXT, ATTENTION_OUTPUT, ATTENTION_RESIDUAL
 * - FFN_NORM, FFN_GATE, FFN_UP, FFN_SWIGLU, FFN_DOWN, FFN_RESIDUAL
 * - FINAL_NORM, LM_HEAD
 *
 * Requirements:
 * - PyTorch snapshots: run `python3 python/reference/generate_qwen2_pipeline_snapshots.py --output pytorch_qwen2_snapshots`
 * - Qwen 2.5 0.5B model: models/qwen2.5-0.5b-instruct-q4_0.gguf
 * - Single-rank execution (no MPI distribution)
 */

#include <gtest/gtest.h>
#include <memory>
#include <vector>
#include <cmath>
#include <cstring>
#include <fstream>
#include <sstream>
#include <unordered_map>

#include "../../../src/v2/loaders/ModelContext.h"
#include "../../../src/v2/pipelines/qwen/Qwen2Pipeline.h"
#include "../../../src/v2/utils/Logger.h"

// NumPy .npz file loading (simple C++ implementation)
#include <cnpy.h>

using namespace llaminar2;

/**
 * @brief Test fixture for Qwen2 FP32 parity against PyTorch
 */
class Qwen2FP32Parity : public ::testing::Test
{
protected:
    void SetUp() override
    {
        // Snapshot directory (generated by Python script)
        snapshot_dir_ = "pytorch_qwen2_snapshots";

        // Model path
        model_path_ = "models/qwen2.5-0.5b-instruct-q4_0.gguf";

        // FP32 tolerance (PyTorch FP32 vs Llaminar FP32)
        tolerance_rel_l2_ = 1e-4f;
        tolerance_max_abs_ = 1e-3f;

        // Regenerate PyTorch snapshots to ensure they match the GGUF model
        regeneratePyTorchSnapshots();
    }

    /**
     * @brief Regenerate PyTorch snapshots from the same GGUF model
     *
     * This ensures we're comparing C++ vs Python using IDENTICAL weights,
     * avoiding the FP32 vs Q4_0 mismatch issue discovered on 2025-11-07.
     */
    void regeneratePyTorchSnapshots()
    {
        LOG_INFO("[Parity] Regenerating PyTorch snapshots from GGUF: " << model_path_);

        // Build command to regenerate snapshots
        std::ostringstream cmd;
#ifdef PYTHON_EXECUTABLE
        cmd << PYTHON_EXECUTABLE;
#else
        cmd << "python3";
#endif
        cmd << " python/reference/generate_qwen2_pipeline_snapshots.py "
            << "--model " << model_path_ << " "
            << "--output " << snapshot_dir_ << " "
            << "--layers 0 " // Just layer 0 for now (faster)
            << "2>&1";       // Capture stderr too

        LOG_DEBUG("[Parity] Running: " << cmd.str());

        // Execute Python script
        FILE *pipe = popen(cmd.str().c_str(), "r");
        if (!pipe)
        {
            LOG_ERROR("[Parity] Failed to execute snapshot generator");
            return;
        }

        // Read output
        char buffer[256];
        std::string output;
        while (fgets(buffer, sizeof(buffer), pipe) != nullptr)
        {
            output += buffer;
        }

        int exit_code = pclose(pipe);

        if (exit_code != 0)
        {
            LOG_ERROR("[Parity] Snapshot generation failed (exit code " << exit_code << "):");
            LOG_ERROR(output);
        }
        else
        {
            LOG_INFO("[Parity] Snapshots regenerated successfully");
            LOG_DEBUG("[Parity] Output:\n"
                      << output);
        }
    }

    void TearDown() override
    {
        model_ctx_.reset();
        pipeline_.reset();
        pytorch_snapshots_.clear();
    }

    /**
     * @brief Comparison result structure
     */
    struct ComparisonResult
    {
        bool passed = false;
        float max_abs_diff = 0.0f;
        float mean_abs_diff = 0.0f;
        float rel_l2_norm = 0.0f;
        size_t num_mismatches = 0;
        size_t total_elements = 0;
    };

    /**
     * @brief Load PyTorch snapshot from .npy file
     *
     * @param name Stage name (e.g., "EMBEDDING", "layer0_Q_PROJECTION")
     * @return Vector of FP32 values
     */
    std::vector<float> loadPyTorchSnapshot(const std::string &name)
    {
        // Check if already loaded
        if (pytorch_snapshots_.find(name) != pytorch_snapshots_.end())
        {
            return pytorch_snapshots_[name];
        }

        // Load from .npy file
        std::string npy_path = snapshot_dir_ + "/" + name + ".npy";

        try
        {
            cnpy::NpyArray arr = cnpy::npy_load(npy_path);

            // Convert to float vector
            std::vector<float> data;
            if (arr.word_size == sizeof(float))
            {
                float *data_ptr = arr.data<float>();
                data.assign(data_ptr, data_ptr + arr.num_vals);
            }
            else if (arr.word_size == sizeof(double))
            {
                // Convert double to float
                double *data_ptr = arr.data<double>();
                data.resize(arr.num_vals);
                for (size_t i = 0; i < arr.num_vals; ++i)
                {
                    data[i] = static_cast<float>(data_ptr[i]);
                }
            }
            else
            {
                LOG_ERROR("[Parity] Unsupported data type in snapshot '" << name << "'");
                return {};
            }

            // Cache for future use
            pytorch_snapshots_[name] = data;

            LOG_DEBUG("[Parity] Loaded snapshot '" << name << "': " << data.size() << " elements");
            return data;
        }
        catch (const std::exception &e)
        {
            LOG_ERROR("[Parity] Failed to load snapshot '" << name << "': " << e.what());
            return {};
        }
    }

    /**
     * @brief Compare Llaminar tensor against PyTorch snapshot
     *
     * @param actual Llaminar tensor data
     * @param expected PyTorch snapshot data
     * @param size Number of elements
     * @return Comparison result
     */
    ComparisonResult compareTensors(
        const float *actual,
        const std::vector<float> &expected,
        size_t size)
    {
        ComparisonResult result;
        result.total_elements = size;

        if (expected.empty())
        {
            LOG_ERROR("[Parity] PyTorch snapshot is empty");
            return result;
        }

        if (expected.size() != size)
        {
            LOG_ERROR("[Parity] Size mismatch: Llaminar=" << size
                                                          << ", PyTorch=" << expected.size());
            return result;
        }

        double sum_abs_diff = 0.0;
        double sum_sq_diff = 0.0;
        double sum_sq_expected = 0.0;

        for (size_t i = 0; i < size; ++i)
        {
            float diff = std::abs(actual[i] - expected[i]);

            if (diff > tolerance_max_abs_)
            {
                result.num_mismatches++;
            }

            if (diff > result.max_abs_diff)
            {
                result.max_abs_diff = diff;
            }

            sum_abs_diff += diff;
            sum_sq_diff += diff * diff;
            sum_sq_expected += expected[i] * expected[i];
        }

        result.mean_abs_diff = static_cast<float>(sum_abs_diff / size);

        // Relative L2 norm: ||actual - expected||_2 / ||expected||_2
        if (sum_sq_expected > 1e-10)
        {
            result.rel_l2_norm = static_cast<float>(std::sqrt(sum_sq_diff / sum_sq_expected));
        }

        // Pass if both tolerances satisfied
        result.passed = (result.max_abs_diff <= tolerance_max_abs_ &&
                         result.rel_l2_norm <= tolerance_rel_l2_);

        return result;
    }

    /**
     * @brief Print comparison result
     */
    void printComparisonResult(const ComparisonResult &result, const std::string &name)
    {
        std::cout << "=== " << name << " ===" << std::endl;
        std::cout << "  Elements:       " << result.total_elements << std::endl;
        std::cout << "  Max abs diff:   " << result.max_abs_diff << std::endl;
        std::cout << "  Mean abs diff:  " << result.mean_abs_diff << std::endl;
        std::cout << "  Rel L2 norm:    " << result.rel_l2_norm << std::endl;
        std::cout << "  Mismatches:     " << result.num_mismatches << " / " << result.total_elements;
        std::cout << " (" << (100.0f * result.num_mismatches / result.total_elements) << "%)" << std::endl;
        std::cout << "  Status:         " << (result.passed ? "✓ PASSED" : "✗ FAILED") << std::endl;
    }

    /**
     * @brief Load model and create pipeline
     */
    bool setupPipeline()
    {
        model_ctx_ = ModelContext::create(model_path_);
        if (!model_ctx_)
        {
            LOG_ERROR("[Parity] Failed to load model: " << model_path_);
            return false;
        }

        // Create FP32 Qwen2Pipeline (single-rank, CPU, batch_size=1)
        pipeline_ = std::make_unique<Qwen2Pipeline>(
            model_ctx_,
            nullptr, // No MPI context (single-rank)
            -1,      // CPU device
            nullptr, // No weight placement
            PipelineConfig{},
            1 // batch_size=1
        );

#ifdef ENABLE_PIPELINE_SNAPSHOTS
        // Enable snapshot capture for parity testing
        pipeline_->enableSnapshotCapture();
        LOG_INFO("[Parity] Snapshot capture enabled");
#else
        LOG_WARN("[Parity] Snapshot capture not available (ENABLE_PIPELINE_SNAPSHOTS not defined)");
#endif

        LOG_INFO("[Parity] Qwen2Pipeline created successfully");
        return true;
    }

    /**
     * @brief Read token IDs from PyTorch metadata
     *
     * Returns the token IDs used by PyTorch to generate snapshots.
     * These are extracted from metadata.txt in the snapshot directory.
     */
    std::vector<int> readTokenIdsFromMetadata()
    {
        // For now, hardcode the default prompt tokens
        // TODO: Parse from metadata.txt

        // Default prompt: "The quick brown fox jumps over the lazy dog"
        // Token IDs: [785, 3974, 13876, 38835, 34208, 916, 279, 15678, 5562]
        return {785, 3974, 13876, 38835, 34208, 916, 279, 15678, 5562};
    }

    // Test state
    std::string snapshot_dir_;
    std::string model_path_;
    float tolerance_rel_l2_;
    float tolerance_max_abs_;

    std::shared_ptr<ModelContext> model_ctx_;
    std::unique_ptr<Qwen2Pipeline> pipeline_;
    std::unordered_map<std::string, std::vector<float>> pytorch_snapshots_;
};

/**
 * @brief Test: Embedding layer parity
 *
 * Validates that Qwen2Pipeline's embedding layer produces identical output to PyTorch.
 */
TEST_F(Qwen2FP32Parity, EmbeddingLayer)
{
    // Setup
    ASSERT_TRUE(setupPipeline());

    // Get token IDs (same as PyTorch)
    std::vector<int> tokens = readTokenIdsFromMetadata();
    ASSERT_FALSE(tokens.empty()) << "Failed to read token IDs";

    LOG_INFO("[Parity] Testing with " << tokens.size() << " tokens");

    // Run pipeline forward pass
    bool success = pipeline_->forward(tokens.data(), tokens.size());
    ASSERT_TRUE(success) << "Pipeline forward pass failed";

    // Load PyTorch embedding snapshot
    auto pytorch_embedding = loadPyTorchSnapshot("EMBEDDING");
    ASSERT_FALSE(pytorch_embedding.empty()) << "Failed to load PyTorch EMBEDDING snapshot";

#ifdef ENABLE_PIPELINE_SNAPSHOTS
    // Get embedding snapshot from pipeline
    size_t llaminar_size;
    const float *llaminar_embedding = pipeline_->getSnapshot("EMBEDDING", llaminar_size);
    ASSERT_NE(llaminar_embedding, nullptr) << "Failed to get EMBEDDING snapshot from pipeline";

    // Compare
    auto result = compareTensors(llaminar_embedding, pytorch_embedding, llaminar_size);
    printComparisonResult(result, "EMBEDDING");

    EXPECT_TRUE(result.passed)
        << "EMBEDDING parity failed: rel_l2=" << result.rel_l2_norm
        << ", max_abs=" << result.max_abs_diff;
#else
    GTEST_SKIP() << "Snapshot capture not enabled (build with ENABLE_PIPELINE_SNAPSHOTS)";
#endif
}

/**
 * @brief Test: Layer 0 attention block parity
 *
 * Validates all attention stages for layer 0:
 * - ATTENTION_NORM
 * - Q_PROJECTION, K_PROJECTION, V_PROJECTION
 * - Q_ROPE, K_ROPE
 * - ATTENTION_CONTEXT, ATTENTION_OUTPUT
 * - ATTENTION_RESIDUAL
 */
TEST_F(Qwen2FP32Parity, Layer0_AttentionBlock)
{
    // Setup
    ASSERT_TRUE(setupPipeline());

    // Get token IDs
    std::vector<int> tokens = readTokenIdsFromMetadata();
    ASSERT_FALSE(tokens.empty());

    // Run pipeline
    bool success = pipeline_->forward(tokens.data(), tokens.size());
    ASSERT_TRUE(success);

#ifdef ENABLE_PIPELINE_SNAPSHOTS
    // List of attention stages to validate
    std::vector<std::string> attention_stages = {
        "ATTENTION_NORM",
        "Q_PROJECTION",
        "K_PROJECTION",
        "V_PROJECTION",
        "Q_ROPE",
        "K_ROPE",
        "ATTENTION_CONTEXT",
        "ATTENTION_OUTPUT",
        "ATTENTION_RESIDUAL"};

    int layer_idx = 0;
    int passed_count = 0;
    int failed_count = 0;

    for (const auto &stage : attention_stages)
    {
        std::string snapshot_name = "layer" + std::to_string(layer_idx) + "_" + stage;

        // Load PyTorch snapshot
        auto pytorch_data = loadPyTorchSnapshot(snapshot_name);
        if (pytorch_data.empty())
        {
            LOG_ERROR("[Parity] Failed to load PyTorch snapshot: " << snapshot_name);
            failed_count++;
            continue;
        }

        // Get Llaminar snapshot
        size_t llaminar_size;
        const float *llaminar_data = pipeline_->getSnapshot(snapshot_name, llaminar_size);
        if (llaminar_data == nullptr)
        {
            LOG_ERROR("[Parity] Failed to get Llaminar snapshot: " << snapshot_name);
            failed_count++;
            continue;
        }

        // Compare
        auto result = compareTensors(llaminar_data, pytorch_data, llaminar_size);
        printComparisonResult(result, snapshot_name);

        // DEBUG: Print sample values on mismatch
        if (!result.passed && snapshot_name.find("Q_PROJECTION") != std::string::npos)
        {
            LOG_INFO("[DEBUG] " << snapshot_name << " sample values:");
            LOG_INFO("[DEBUG]   Llaminar first 10: " << llaminar_data[0] << ", " << llaminar_data[1] << ", "
                                                     << llaminar_data[2] << ", " << llaminar_data[3] << ", " << llaminar_data[4] << ", "
                                                     << llaminar_data[5] << ", " << llaminar_data[6] << ", " << llaminar_data[7] << ", "
                                                     << llaminar_data[8] << ", " << llaminar_data[9]);
            LOG_INFO("[DEBUG]   PyTorch first 10: " << pytorch_data[0] << ", " << pytorch_data[1] << ", "
                                                    << pytorch_data[2] << ", " << pytorch_data[3] << ", " << pytorch_data[4] << ", "
                                                    << pytorch_data[5] << ", " << pytorch_data[6] << ", " << pytorch_data[7] << ", "
                                                    << pytorch_data[8] << ", " << pytorch_data[9]);
        }

        if (result.passed)
        {
            passed_count++;
        }
        else
        {
            failed_count++;
            // Stop at first failure for easier debugging
            EXPECT_TRUE(false)
                << "First divergence at " << snapshot_name
                << ": rel_l2=" << result.rel_l2_norm
                << ", max_abs=" << result.max_abs_diff;
            break;
        }
    }

    LOG_INFO("[Parity] Attention block: " << passed_count << "/" << attention_stages.size() << " stages passed");
    EXPECT_EQ(failed_count, 0) << "Some attention stages failed parity check";
#else
    GTEST_SKIP() << "Snapshot capture not enabled (build with ENABLE_PIPELINE_SNAPSHOTS)";
#endif
}

/**
 * @brief Test: Layer 0 FFN block parity
 *
 * Validates all FFN stages for layer 0:
 * - FFN_NORM
 * - FFN_GATE, FFN_UP
 * - FFN_SWIGLU
 * - FFN_DOWN
 * - FFN_RESIDUAL
 */
TEST_F(Qwen2FP32Parity, Layer0_FFNBlock)
{
    // Setup
    ASSERT_TRUE(setupPipeline());

    // Get token IDs
    std::vector<int> tokens = readTokenIdsFromMetadata();
    ASSERT_FALSE(tokens.empty());

    // Run pipeline
    bool success = pipeline_->forward(tokens.data(), tokens.size());
    ASSERT_TRUE(success);

    // List of FFN stages to validate
    std::vector<std::string> ffn_stages = {
        "FFN_NORM",
        "FFN_GATE",
        "FFN_UP",
        "FFN_SWIGLU",
        "FFN_DOWN",
        "FFN_RESIDUAL"};

    int layer_idx = 0;
    int passed_count = 0;
    int failed_count = 0;

#ifdef ENABLE_PIPELINE_SNAPSHOTS
    for (const auto &stage : ffn_stages)
    {
        std::string snapshot_name = "layer" + std::to_string(layer_idx) + "_" + stage;

        // Load PyTorch snapshot
        auto pytorch_data = loadPyTorchSnapshot(snapshot_name);
        if (pytorch_data.empty())
        {
            LOG_ERROR("[Parity] Failed to load PyTorch snapshot: " << snapshot_name);
            failed_count++;
            continue;
        }

        // Get Llaminar snapshot
        size_t llaminar_size;
        const float *llaminar_data = pipeline_->getSnapshot(snapshot_name, llaminar_size);
        if (llaminar_data == nullptr)
        {
            LOG_ERROR("[Parity] Failed to get Llaminar snapshot: " << snapshot_name);
            failed_count++;
            continue;
        }

        // Compare
        auto result = compareTensors(llaminar_data, pytorch_data, llaminar_size);
        printComparisonResult(result, snapshot_name);

        if (result.passed)
        {
            passed_count++;
        }
        else
        {
            failed_count++;
            // Stop at first failure for easier debugging
            EXPECT_TRUE(false)
                << "First divergence at " << snapshot_name
                << ": rel_l2=" << result.rel_l2_norm
                << ", max_abs=" << result.max_abs_diff;
            break;
        }
    }

    LOG_INFO("[Parity] FFN block: " << passed_count << "/" << ffn_stages.size() << " stages passed");
    EXPECT_EQ(failed_count, 0) << "Some FFN stages failed parity check";
#else
    GTEST_SKIP() << "Snapshot capture not enabled (build with ENABLE_PIPELINE_SNAPSHOTS)";
#endif
}

/**
 * @brief Test: Final norm and LM head parity
 *
 * Validates:
 * - FINAL_NORM: RMSNorm output after all transformer layers
 * - LM_HEAD: Logits over vocabulary
 */
TEST_F(Qwen2FP32Parity, FinalNormAndLogits)
{
    // Setup
    ASSERT_TRUE(setupPipeline());

    // Get token IDs
    std::vector<int> tokens = readTokenIdsFromMetadata();
    ASSERT_FALSE(tokens.empty());

    // Run pipeline
    bool success = pipeline_->forward(tokens.data(), tokens.size());
    ASSERT_TRUE(success);

#ifdef ENABLE_PIPELINE_SNAPSHOTS
    // Test FINAL_NORM
    {
        auto pytorch_final_norm = loadPyTorchSnapshot("FINAL_NORM");
        ASSERT_FALSE(pytorch_final_norm.empty()) << "Failed to load FINAL_NORM snapshot";

        size_t llaminar_size;
        const float *llaminar_final_norm = pipeline_->getSnapshot("FINAL_NORM", llaminar_size);
        ASSERT_NE(llaminar_final_norm, nullptr) << "Failed to get FINAL_NORM snapshot";

        auto result = compareTensors(llaminar_final_norm, pytorch_final_norm, llaminar_size);
        printComparisonResult(result, "FINAL_NORM");

        EXPECT_TRUE(result.passed)
            << "FINAL_NORM parity failed: rel_l2=" << result.rel_l2_norm
            << ", max_abs=" << result.max_abs_diff;
    }

    // Test LM_HEAD (logits)
    {
        auto pytorch_logits = loadPyTorchSnapshot("LM_HEAD");
        ASSERT_FALSE(pytorch_logits.empty()) << "Failed to load LM_HEAD snapshot";

        size_t llaminar_size;
        const float *llaminar_logits = pipeline_->getSnapshot("LM_HEAD", llaminar_size);
        ASSERT_NE(llaminar_logits, nullptr) << "Failed to get LM_HEAD snapshot";

        auto result = compareTensors(llaminar_logits, pytorch_logits, llaminar_size);
        printComparisonResult(result, "LM_HEAD");

        EXPECT_TRUE(result.passed)
            << "LM_HEAD parity failed: rel_l2=" << result.rel_l2_norm
            << ", max_abs=" << result.max_abs_diff;
    }
#else
    GTEST_SKIP() << "Snapshot capture not enabled (build with ENABLE_PIPELINE_SNAPSHOTS)";
#endif
}

/**
 * @brief Test: Complete pipeline parity (all layers)
 *
 * Validates all intermediate activations across all 24 transformer layers.
 * This is the comprehensive end-to-end validation test.
 */
TEST_F(Qwen2FP32Parity, DISABLED_AllLayersParity)
{
    // This test is disabled by default (runs all 24 layers × 17 stages = 408 comparisons)
    // Enable manually for comprehensive validation

    ASSERT_TRUE(setupPipeline());

    std::vector<int> tokens = readTokenIdsFromMetadata();
    ASSERT_FALSE(tokens.empty());

    bool success = pipeline_->forward(tokens.data(), tokens.size());
    ASSERT_TRUE(success);

    int n_layers = model_ctx_->model().block_count;

    std::vector<std::string> per_layer_stages = {
        "ATTENTION_NORM", "Q_PROJECTION", "K_PROJECTION", "V_PROJECTION",
        "Q_ROPE", "K_ROPE", "ATTENTION_SCORES", "ATTENTION_SOFTMAX",
        "ATTENTION_CONTEXT", "ATTENTION_OUTPUT", "ATTENTION_RESIDUAL",
        "FFN_NORM", "FFN_GATE", "FFN_UP", "FFN_SWIGLU", "FFN_DOWN", "FFN_RESIDUAL"};

    int total_tests = 0;
    int passed_tests = 0;
    int failed_tests = 0;

    // Test embedding
    {
        auto pytorch_data = loadPyTorchSnapshot("EMBEDDING");
        if (!pytorch_data.empty())
        {
            total_tests++;
            // TODO: Compare
            LOG_WARN("[Parity] EMBEDDING comparison not implemented");
        }
    }

    // Test all layers
    for (int layer_idx = 0; layer_idx < n_layers; ++layer_idx)
    {
        LOG_INFO("[Parity] Testing layer " << layer_idx << "/" << n_layers);

        for (const auto &stage : per_layer_stages)
        {
            std::string snapshot_name = "layer" + std::to_string(layer_idx) + "_" + stage;
            auto pytorch_data = loadPyTorchSnapshot(snapshot_name);

            if (!pytorch_data.empty())
            {
                total_tests++;
                // TODO: Get actual data from pipeline and compare
                LOG_WARN("[Parity] Stage '" << snapshot_name << "' comparison not implemented");
            }
        }
    }

    // Test final norm and logits
    {
        auto pytorch_final_norm = loadPyTorchSnapshot("FINAL_NORM");
        auto pytorch_logits = loadPyTorchSnapshot("LM_HEAD");

        if (!pytorch_final_norm.empty())
            total_tests++;
        if (!pytorch_logits.empty())
            total_tests++;

        // TODO: Compare
    }

    LOG_INFO("[Parity] Complete pipeline validation:");
    LOG_INFO("  Total tests:  " << total_tests);
    LOG_INFO("  Passed:       " << passed_tests);
    LOG_INFO("  Failed:       " << failed_tests);

    GTEST_SKIP() << "Full pipeline instrumentation not yet implemented";
}

/**
 * @brief Test: Snapshot loading infrastructure
 *
 * Validates that PyTorch snapshots can be loaded correctly.
 */
TEST_F(Qwen2FP32Parity, SnapshotLoadingInfrastructure)
{
    // Try loading embedding snapshot
    auto embedding = loadPyTorchSnapshot("EMBEDDING");

    if (embedding.empty())
    {
        GTEST_SKIP() << "PyTorch snapshots not found. Run: python3 python/reference/generate_qwen2_pipeline_snapshots.py --output " << snapshot_dir_;
    }

    // Check embedding size
    // Expected: [batch=1, seq_len=9, d_model=896] = 8064 elements
    EXPECT_EQ(embedding.size(), 1 * 9 * 896) << "EMBEDDING snapshot size mismatch";

    LOG_INFO("[Parity] Successfully loaded EMBEDDING snapshot: " << embedding.size() << " elements");

    // Try loading layer 0 snapshots
    std::vector<std::string> test_stages = {
        "layer0_Q_PROJECTION",
        "layer0_ATTENTION_RESIDUAL",
        "layer0_FFN_RESIDUAL"};

    for (const auto &stage : test_stages)
    {
        auto data = loadPyTorchSnapshot(stage);
        EXPECT_FALSE(data.empty()) << "Failed to load " << stage;
        LOG_INFO("[Parity] Loaded " << stage << ": " << data.size() << " elements");
    }

    // Try loading final stages
    auto final_norm = loadPyTorchSnapshot("FINAL_NORM");
    auto lm_head = loadPyTorchSnapshot("LM_HEAD");

    EXPECT_FALSE(final_norm.empty()) << "Failed to load FINAL_NORM";
    EXPECT_FALSE(lm_head.empty()) << "Failed to load LM_HEAD";

    // Expected: LM_HEAD = [batch=1, seq_len=9, vocab_size=151936] = 1367424 elements
    EXPECT_EQ(lm_head.size(), 1 * 9 * 151936) << "LM_HEAD snapshot size mismatch";

    LOG_INFO("[Parity] Successfully loaded FINAL_NORM: " << final_norm.size() << " elements");
    LOG_INFO("[Parity] Successfully loaded LM_HEAD: " << lm_head.size() << " elements");
}
