/**
 * @file DynamicThresholdLoader.h
 * @brief Load variance-based dynamic thresholds for parity tests
 * @author David Sanftenberg
 *
 * This utility loads thresholds generated by the variance analysis script
 * and provides per-stage tolerance values for parity testing.
 */

#pragma once

#include <string>
#include <unordered_map>
#include <filesystem>
#include <fstream>
#include <iostream>

namespace llaminar
{
    namespace parity
    {

        /**
         * @brief Threshold values for a single stage
         */
        struct StageThreshold
        {
            float max_abs;
            double rel_l2;

            StageThreshold() : max_abs(0.1f), rel_l2(0.05) {}
            StageThreshold(float ma, double rl) : max_abs(ma), rel_l2(rl) {}
        };

        /**
         * @brief Loads and manages dynamic thresholds from JSON file
         *
         * Supports variance-based thresholds from generate_variance_thresholds.py
         * with fallback to conservative defaults.
         */
        class DynamicThresholdLoader
        {
        public:
            /**
             * @brief Load thresholds from JSON file
             *
             * Expected JSON format:
             * {
             *   "STAGE_NAME": {
             *     "max_abs": 0.123,
             *     "rel_l2": 0.05,
             *     "variance_metric": 0.0246,
             *     "magnitude_threshold": 0.0789
             *   },
             *   ...
             * }
             *
             * @param json_path Path to dynamic_thresholds.json
             * @return true if loaded successfully, false if fallback to defaults
             */
            bool load(const std::string &json_path)
            {
                namespace fs = std::filesystem;

                if (!fs::exists(json_path))
                {
                    std::cerr << "[DynamicThresholds] WARNING: " << json_path << " not found" << std::endl;
                    std::cerr << "[DynamicThresholds] Using conservative default thresholds" << std::endl;
                    use_defaults_ = true;
                    return false;
                }

                std::ifstream file(json_path);
                if (!file.is_open())
                {
                    std::cerr << "[DynamicThresholds] WARNING: Failed to open " << json_path << std::endl;
                    std::cerr << "[DynamicThresholds] Using conservative default thresholds" << std::endl;
                    use_defaults_ = true;
                    return false;
                }

                // Simple JSON parsing (just enough for our use case)
                // Format: {"STAGE_NAME": {"max_abs": X, "rel_l2": Y}, ...}
                std::string line;
                std::string current_stage;

                while (std::getline(file, line))
                {
                    // Remove whitespace
                    line.erase(std::remove_if(line.begin(), line.end(), ::isspace), line.end());

                    if (line.empty() || line == "{" || line == "}" || line == "},")
                    {
                        continue;
                    }

                    // Check for stage name (starts with quote, ends with ":{)
                    if (line.find("\"") == 0 && line.find("\":{") != std::string::npos)
                    {
                        size_t end_quote = line.find("\"", 1);
                        current_stage = line.substr(1, end_quote - 1);
                        continue;
                    }

                    // Check for max_abs
                    if (line.find("\"max_abs\":") != std::string::npos && !current_stage.empty())
                    {
                        size_t colon = line.find(":");
                        std::string value_str = line.substr(colon + 1);
                        // Remove trailing comma if present
                        if (value_str.back() == ',')
                        {
                            value_str.pop_back();
                        }
                        thresholds_[current_stage].max_abs = std::stof(value_str);
                    }

                    // Check for rel_l2
                    if (line.find("\"rel_l2\":") != std::string::npos && !current_stage.empty())
                    {
                        size_t colon = line.find(":");
                        std::string value_str = line.substr(colon + 1);
                        // Remove trailing comma if present
                        if (value_str.back() == ',')
                        {
                            value_str.pop_back();
                        }
                        thresholds_[current_stage].rel_l2 = std::stod(value_str);
                    }
                }

                if (thresholds_.empty())
                {
                    std::cerr << "[DynamicThresholds] WARNING: No thresholds loaded from " << json_path << std::endl;
                    std::cerr << "[DynamicThresholds] Using conservative default thresholds" << std::endl;
                    use_defaults_ = true;
                    return false;
                }

                std::cout << "[DynamicThresholds] Loaded " << thresholds_.size()
                          << " stage thresholds from " << json_path << std::endl;
                use_defaults_ = false;
                return true;
            }

            /**
             * @brief Get threshold for a specific stage
             *
             * @param stage_name Stage name (e.g., "ATTENTION_SCORES_0")
             * @return StageThreshold with max_abs and rel_l2 values
             */
            StageThreshold get_threshold(const std::string &stage_name) const
            {
                if (use_defaults_)
                {
                    return get_default_threshold(stage_name);
                }

                auto it = thresholds_.find(stage_name);
                if (it != thresholds_.end())
                {
                    return it->second;
                }

                // Fallback to default
                return get_default_threshold(stage_name);
            }

            /**
             * @brief Get all loaded thresholds
             */
            const std::unordered_map<std::string, StageThreshold> &get_all_thresholds() const
            {
                return thresholds_;
            }

            /**
             * @brief Check if using defaults (JSON not loaded)
             */
            bool using_defaults() const
            {
                return use_defaults_;
            }

        private:
            /**
             * @brief Get conservative default threshold for a stage
             *
             * Uses pattern matching on stage name to provide reasonable defaults.
             */
            StageThreshold get_default_threshold(const std::string &stage_name) const
            {
                // Tight tolerance for normalization stages
                if (stage_name.find("NORM") != std::string::npos)
                {
                    return StageThreshold(0.05f, 0.02);
                }

                // Tight tolerance for embedding
                if (stage_name.find("EMBEDDING") != std::string::npos)
                {
                    return StageThreshold(0.05f, 0.02);
                }

                // Relaxed for attention scores (high magnitude)
                if (stage_name.find("ATTENTION_SCORES") != std::string::npos)
                {
                    return StageThreshold(5.5f, 0.05); // Variance analysis showed ~5.39
                }

                // Relaxed for ROPE (moderate magnitude)
                if (stage_name.find("ROPE_APPLICATION") != std::string::npos)
                {
                    return StageThreshold(0.21f, 0.05); // Variance analysis showed ~0.205
                }

                // Relaxed for K projection (high magnitude)
                if (stage_name.find("K_PROJECTION") != std::string::npos)
                {
                    return StageThreshold(0.50f, 0.05); // Variance analysis showed ~0.487
                }

                // Relaxed for Q/V projections (quantization effects)
                if (stage_name.find("Q_PROJECTION") != std::string::npos ||
                    stage_name.find("V_PROJECTION") != std::string::npos)
                {
                    return StageThreshold(0.15f, 0.05);
                }

                // Relaxed for final LM_HEAD
                if (stage_name.find("LM_HEAD") != std::string::npos)
                {
                    return StageThreshold(0.15f, 0.1);
                }

                // Default for everything else
                return StageThreshold(0.1f, 0.05);
            }

            std::unordered_map<std::string, StageThreshold> thresholds_;
            bool use_defaults_ = true;
        };

    } // namespace parity
} // namespace llaminar
