/**
 * @file Test__FP32AttentionParity.cpp
 * @brief PyTorch parity test for FP32 attention kernel
 * @author David Sanftenberg
 * @date 2025-11-06
 *
 * This test validates FP32AttentionKernel against PyTorch ground truth.
 * It loads PyTorch snapshots generated by python/reference/generate_attention_snapshots.py
 * and compares intermediate states to ensure mathematical correctness.
 *
 * Test strategy:
 * 1. Generate PyTorch snapshots using: python3 python/reference/generate_attention_snapshots.py
 * 2. Load snapshots in C++ using NpzLoader
 * 3. Run FP32AttentionKernel with same Q/K/V inputs
 * 4. Compare outputs with tight tolerances (rel_l2 < 1e-4)
 *
 * This establishes FP32AttentionKernel as a validated reference before testing INT8.
 */

#include <gtest/gtest.h>
#include "../../../src/v2/kernels/cpu/FP32AttentionKernel.h"
#include "../../../src/v2/utils/Logger.h"
#include "../pytorch_parity/NpzLoader.h"

#include <memory>
#include <cmath>
#include <vector>
#include <algorithm>
#include <filesystem>
#include <iostream>
#include <iomanip>

using namespace llaminar2;
using namespace llaminar::parity;

// ============================================================================
// Test Fixture
// ============================================================================

class Test__FP32AttentionParity : public ::testing::Test
{
protected:
    std::string snapshot_dir_ = "pytorch_attention_snapshots";

    void SetUp() override
    {
        // Check if snapshots exist
        if (!std::filesystem::exists(snapshot_dir_))
        {
            GTEST_SKIP() << "PyTorch snapshots not found. Generate with:\n"
                         << "  python3 python/reference/generate_attention_snapshots.py";
        }
    }

    // Helper: Load .npy snapshot
    bool load_snapshot(const std::string &name, NpyArray &out)
    {
        std::string filepath = snapshot_dir_ + "/" + name + ".npy";
        if (!NpzLoader::load_npy(filepath, out))
        {
            LOG_ERROR("Failed to load snapshot: " << filepath);
            return false;
        }
        return true;
    }

    // Helper: Compute relative L2 error
    float compute_relative_l2(const std::vector<float> &expected, const std::vector<float> &actual)
    {
        if (expected.size() != actual.size())
        {
            LOG_ERROR("Size mismatch: expected=" << expected.size() << " actual=" << actual.size());
            return std::numeric_limits<float>::infinity();
        }

        float sum_sq_error = 0.0f;
        float sum_sq_expected = 0.0f;

        for (size_t i = 0; i < expected.size(); ++i)
        {
            float error = actual[i] - expected[i];
            sum_sq_error += error * error;
            sum_sq_expected += expected[i] * expected[i];
        }

        if (sum_sq_expected < 1e-12f)
        {
            return std::sqrt(sum_sq_error);
        }

        return std::sqrt(sum_sq_error / sum_sq_expected);
    }

    // Helper: Compute max absolute difference
    float compute_max_abs_diff(const std::vector<float> &expected, const std::vector<float> &actual)
    {
        if (expected.size() != actual.size())
        {
            return std::numeric_limits<float>::infinity();
        }

        float max_diff = 0.0f;
        for (size_t i = 0; i < expected.size(); ++i)
        {
            max_diff = std::max(max_diff, std::abs(actual[i] - expected[i]));
        }
        return max_diff;
    }

    // Helper: Print comparison summary
    void print_comparison(
        const std::string &stage_name,
        const std::vector<float> &expected,
        const std::vector<float> &actual,
        float max_abs_threshold,
        float rel_l2_threshold)
    {
        float max_abs = compute_max_abs_diff(expected, actual);
        float rel_l2 = compute_relative_l2(expected, actual);

        std::cout << "\n=== " << stage_name << " Comparison ===\n";
        std::cout << "  Size: " << expected.size() << " elements\n";
        std::cout << "  Max abs diff: " << std::scientific << std::setprecision(6) << max_abs
                  << " (threshold: " << max_abs_threshold << ")\n";
        std::cout << "  Relative L2:  " << std::scientific << std::setprecision(6) << rel_l2
                  << " (threshold: " << rel_l2_threshold << ")\n";

        // Show first few values
        std::cout << "  Expected[:5]: ";
        for (size_t i = 0; i < std::min(size_t(5), expected.size()); ++i)
        {
            std::cout << std::fixed << std::setprecision(6) << expected[i] << " ";
        }
        std::cout << "\n  Actual[:5]:   ";
        for (size_t i = 0; i < std::min(size_t(5), actual.size()); ++i)
        {
            std::cout << std::fixed << std::setprecision(6) << actual[i] << " ";
        }
        std::cout << "\n";

        if (max_abs <= max_abs_threshold && rel_l2 <= rel_l2_threshold)
        {
            std::cout << "  ✓ PASS\n";
        }
        else
        {
            std::cout << "  ✗ FAIL\n";
        }
    }
};

// ============================================================================
// Parity Tests
// ============================================================================

/**
 * @brief Test basic forward pass against PyTorch
 *
 * Uses snapshots from "Hello world" prompt (2 tokens, seq_len=2).
 * Validates final attention output matches PyTorch within tight tolerances.
 */
TEST_F(Test__FP32AttentionParity, BasicForwardVsPyTorch)
{
    // Load PyTorch snapshots
    NpyArray pytorch_q, pytorch_k, pytorch_v, pytorch_context;

    ASSERT_TRUE(load_snapshot("Q_rope", pytorch_q)) << "Failed to load Q_rope.npy";
    ASSERT_TRUE(load_snapshot("K_rope", pytorch_k)) << "Failed to load K_rope.npy";
    ASSERT_TRUE(load_snapshot("V_projection", pytorch_v)) << "Failed to load V_projection.npy";
    ASSERT_TRUE(load_snapshot("attention_context", pytorch_context)) << "Failed to load attention_context.npy";

    // Extract dimensions from PyTorch snapshots
    // Q_rope shape: [batch, seq_len, n_heads * d_head]
    ASSERT_EQ(pytorch_q.shape.size(), 3) << "Expected Q to be 3D";
    int batch = pytorch_q.shape[0];
    int seq_len = pytorch_q.shape[1];
    int d_model_q = pytorch_q.shape[2];

    // K_rope shape: [batch, seq_len, n_kv_heads * d_head]
    ASSERT_EQ(pytorch_k.shape.size(), 3) << "Expected K to be 3D";
    int d_model_k = pytorch_k.shape[2];

    // Infer n_heads and d_head
    // From Qwen 2.5 0.5B: n_heads=14, n_kv_heads=2, d_head=64
    // d_model_q = 896 = 14 * 64
    // d_model_k = 128 = 2 * 64
    int n_heads = 14; // Qwen 2.5 0.5B
    int d_head = 64;
    int n_kv_heads = d_model_k / d_head;

    ASSERT_EQ(d_model_q, n_heads * d_head) << "Q dimension mismatch";
    ASSERT_EQ(d_model_k, n_kv_heads * d_head) << "K dimension mismatch";

    LOG_INFO("Test configuration:");
    LOG_INFO("  batch=" << batch << ", seq_len=" << seq_len);
    LOG_INFO("  n_heads=" << n_heads << ", n_kv_heads=" << n_kv_heads << ", d_head=" << d_head);

    // Run FP32 attention
    FP32AttentionKernel attn(n_heads, d_head, n_kv_heads); // Pass n_kv_heads!

    std::vector<float> output_actual(batch * seq_len * d_model_q);

    bool success = attn.forward(
        pytorch_q.data.data(),
        pytorch_k.data.data(),
        pytorch_v.data.data(),
        output_actual.data(),
        batch, seq_len,
        false); // No causal mask

    ASSERT_TRUE(success) << "Forward pass failed";

    // Compare output with PyTorch (attention context, not final output projection)
    float max_abs = compute_max_abs_diff(pytorch_context.data, output_actual);
    float rel_l2 = compute_relative_l2(pytorch_context.data, output_actual);

    print_comparison("Attention Context", pytorch_context.data, output_actual, 1e-4f, 1e-4f);

    EXPECT_LT(max_abs, 1e-4f) << "Max absolute difference too large";
    EXPECT_LT(rel_l2, 1e-4f) << "Relative L2 error too large";
}

/**
 * @brief Test attention scores against PyTorch
 *
 * Validates intermediate attention_scores (pre-softmax) match PyTorch.
 * This tests the Q @ K^T / sqrt(d_head) computation.
 */
TEST_F(Test__FP32AttentionParity, AttentionScoresVsPyTorch)
{
    // Load PyTorch snapshots
    NpyArray pytorch_q, pytorch_k, pytorch_v, pytorch_scores;

    ASSERT_TRUE(load_snapshot("Q_rope", pytorch_q));
    ASSERT_TRUE(load_snapshot("K_rope", pytorch_k));
    ASSERT_TRUE(load_snapshot("V_projection", pytorch_v));
    ASSERT_TRUE(load_snapshot("attention_scores", pytorch_scores));

    // Extract dimensions
    int batch = pytorch_q.shape[0];
    int seq_len = pytorch_q.shape[1];
    int d_model_q = pytorch_q.shape[2];
    int d_model_k = pytorch_k.shape[2];

    int n_heads = 14;
    int d_head = 64;

    // Run FP32 attention
    FP32AttentionKernel attn(n_heads, d_head);

    std::vector<float> output_actual(batch * seq_len * d_model_q);

    bool success = attn.forward(
        pytorch_q.data.data(),
        pytorch_k.data.data(),
        pytorch_v.data.data(),
        output_actual.data(),
        batch, seq_len,
        false);

    ASSERT_TRUE(success);

    // Note: We don't have direct access to internal scores_buffer_
    // This test verifies the final output includes correct score computation
    // For deeper validation, we'd need to expose intermediate buffers or use
    // a debug mode. For now, we rely on final output correctness.

    LOG_INFO("AttentionScores test: Validated via final output correctness");
}

/**
 * @brief Test with causal masking
 *
 * Validates that causal masking produces different (and correct) output.
 */
TEST_F(Test__FP32AttentionParity, CausalMaskingVsPyTorch)
{
    // Generate PyTorch snapshots with --causal flag first!
    std::string causal_snapshot_dir = "pytorch_attention_snapshots_causal";

    if (!std::filesystem::exists(causal_snapshot_dir))
    {
        GTEST_SKIP() << "Causal snapshots not found. Generate with:\n"
                     << "  python3 python/reference/generate_attention_snapshots.py --causal --output " << causal_snapshot_dir;
    }

    // Load causal snapshots
    NpyArray pytorch_q, pytorch_k, pytorch_v, pytorch_output_causal;

    auto load_snapshot_causal = [&](const std::string &name, NpyArray &out) -> bool
    {
        std::string filepath = causal_snapshot_dir + "/" + name + ".npy";
        return NpzLoader::load_npy(filepath, out);
    };

    ASSERT_TRUE(load_snapshot_causal("Q_rope", pytorch_q));
    ASSERT_TRUE(load_snapshot_causal("K_rope", pytorch_k));
    ASSERT_TRUE(load_snapshot_causal("V_projection", pytorch_v));
    ASSERT_TRUE(load_snapshot_causal("attention_output", pytorch_output_causal));

    // Extract dimensions
    int batch = pytorch_q.shape[0];
    int seq_len = pytorch_q.shape[1];
    int d_model_q = pytorch_q.shape[2];

    int n_heads = 14;
    int d_head = 64;
    int n_kv_heads = pytorch_k.shape[2] / d_head; // Infer from K

    // Run FP32 attention with causal mask
    FP32AttentionKernel attn(n_heads, d_head, n_kv_heads);

    std::vector<float> output_causal(batch * seq_len * d_model_q);

    bool success = attn.forward(
        pytorch_q.data.data(),
        pytorch_k.data.data(),
        pytorch_v.data.data(),
        output_causal.data(),
        batch, seq_len,
        true); // Causal mask

    ASSERT_TRUE(success);

    // Compare with PyTorch causal output
    float max_abs = compute_max_abs_diff(pytorch_output_causal.data, output_causal);
    float rel_l2 = compute_relative_l2(pytorch_output_causal.data, output_causal);

    print_comparison("Causal Attention Output", pytorch_output_causal.data, output_causal, 1e-4f, 1e-4f);

    EXPECT_LT(max_abs, 1e-4f);
    EXPECT_LT(rel_l2, 1e-4f);
}

/**
 * @brief Test edge case: single sequence (seq_len=1)
 *
 * With seq_len=1, attention weights should be [1.0], and output should match V exactly.
 */
TEST_F(Test__FP32AttentionParity, SingleSequenceEdgeCase)
{
    // For this test, we need to generate snapshots with a single-token prompt
    // Skip if not available
    std::string single_snapshot_dir = "pytorch_attention_snapshots_single";

    if (!std::filesystem::exists(single_snapshot_dir))
    {
        GTEST_SKIP() << "Single-token snapshots not found. Generate with:\n"
                     << "  python3 python/reference/generate_attention_snapshots.py --prompt 'A' --output " << single_snapshot_dir;
    }

    LOG_INFO("SingleSequence test: Requires single-token snapshots (skipped for now)");
}

// ============================================================================
// Main Test Entry Point
// ============================================================================

int main(int argc, char **argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
