#!/usr/bin/env python3
"""
Export CPU GEMM ML Heuristic to C++ Header

Converts trained ONNX model to C++ header file with embedded weights,
enabling lightweight inference without ONNX runtime dependency.

Input: cpu_gemm_heuristic.onnx, cpu_gemm_scaler.npz
Output: src/v2/kernels/cpu/CpuGemmHeuristicWeights.h

Usage:
    ./export_cpu_heuristic.py --model cpu_gemm_heuristic.onnx

Author: David Sanftenberg
Date: November 2025
"""

import argparse
import onnx
import numpy as np
from onnx import numpy_helper
import sys
from pathlib import Path

def extract_weights(onnx_path):
    """Extract weight matrices and biases from ONNX model"""
    
    print(f"Loading ONNX model: {onnx_path}")
    model = onnx.load(onnx_path)
    
    # Extract initializers (weights and biases)
    weights = {}
    for init in model.graph.initializer:
        tensor = numpy_helper.to_array(init)
        weights[init.name] = tensor
        print(f"  {init.name}: shape {tensor.shape}, dtype {tensor.dtype}")
    
    # Organize weights by layer
    layers = []
    layer_idx = 0
    
    # Find weight/bias pairs
    while True:
        weight_key = f'network.{layer_idx}.weight'
        bias_key = f'network.{layer_idx}.bias'
        
        if weight_key not in weights:
            break
        
        layers.append({
            'weight': weights[weight_key],
            'bias': weights[bias_key]
        })
        
        layer_idx += 3  # Skip ReLU and Dropout layers
    
    print(f"\nExtracted {len(layers)} layers")
    for i, layer in enumerate(layers):
        w_shape = layer['weight'].shape
        b_shape = layer['bias'].shape
        print(f"  Layer {i}: W={w_shape}, b={b_shape}")
    
    return layers

def load_scaler(scaler_path):
    """Load feature scaler parameters"""
    
    print(f"\nLoading scaler: {scaler_path}")
    data = np.load(scaler_path)
    mean = data['mean']
    scale = data['scale']
    
    print(f"  Mean shape: {mean.shape}")
    print(f"  Scale shape: {scale.shape}")
    
    return mean, scale

def format_array_cpp(arr, name, indent=1):
    """Format numpy array as C++ array initializer"""
    
    ind = "    " * indent
    
    if arr.ndim == 1:
        # 1D array
        values = ", ".join(f"{v:.6f}f" for v in arr)
        return f"{ind}static constexpr float {name}[{len(arr)}] = {{\n{ind}    {values}\n{ind}}};"
    
    elif arr.ndim == 2:
        # 2D array (matrix)
        lines = [f"{ind}static constexpr float {name}[{arr.shape[0]}][{arr.shape[1]}] = {{"]
        
        for i, row in enumerate(arr):
            values = ", ".join(f"{v:.6f}f" for v in row)
            comma = "," if i < len(arr) - 1 else ""
            lines.append(f"{ind}    {{{values}}}{comma}")
        
        lines.append(f"{ind}}};")
        return "\n".join(lines)
    
    else:
        raise ValueError(f"Unsupported array dimension: {arr.ndim}")

def generate_header(layers, scaler_mean, scaler_scale, output_path):
    """Generate C++ header file with embedded weights"""
    
    print(f"\nGenerating C++ header: {output_path}")
    
    header = []
    header.append("/**")
    header.append(" * @file CpuGemmHeuristicWeights.h")
    header.append(" * @brief CPU GEMM ML heuristic weights (auto-generated)")
    header.append(" * ")
    header.append(" * This file contains trained neural network weights for predicting")
    header.append(" * optimal micro-kernel variants for CPU GEMM operations.")
    header.append(" * ")
    header.append(" * Generated by: export_cpu_heuristic.py")
    header.append(" * DO NOT EDIT MANUALLY")
    header.append(" * ")
    header.append(" * @author David Sanftenberg")
    header.append(" */")
    header.append("")
    header.append("#pragma once")
    header.append("")
    header.append("#include <cstddef>")
    header.append("#include <cmath>")
    header.append("#include <algorithm>")
    header.append("")
    header.append("namespace llaminar {")
    header.append("namespace cpu {")
    header.append("")
    header.append("/**")
    header.append(" * @brief ML-based heuristic for CPU GEMM variant selection")
    header.append(" * ")
    header.append(" * Trained neural network predicts GFLOPS for given variant configuration.")
    header.append(" * Replaces manual heuristics with data-driven predictions.")
    header.append(" */")
    header.append("class CpuGemmHeuristic {")
    header.append("public:")
    header.append("")
    
    # Feature scaler constants
    header.append("    // Feature normalization parameters")
    header.append(f"    static constexpr size_t NUM_FEATURES = {len(scaler_mean)};")
    header.append("")
    header.append(format_array_cpp(scaler_mean, "SCALER_MEAN"))
    header.append("")
    header.append(format_array_cpp(scaler_scale, "SCALER_SCALE"))
    header.append("")
    
    # Layer dimensions
    header.append("    // Network architecture")
    header.append(f"    static constexpr size_t NUM_LAYERS = {len(layers)};")
    
    for i, layer in enumerate(layers):
        in_size = layer['weight'].shape[1]
        out_size = layer['weight'].shape[0]
        header.append(f"    static constexpr size_t LAYER{i}_IN = {in_size};")
        header.append(f"    static constexpr size_t LAYER{i}_OUT = {out_size};")
    
    header.append("")
    
    # Layer weights and biases
    for i, layer in enumerate(layers):
        header.append(f"    // Layer {i}")
        header.append(format_array_cpp(layer['weight'], f"LAYER{i}_WEIGHT"))
        header.append("")
        header.append(format_array_cpp(layer['bias'], f"LAYER{i}_BIAS"))
        header.append("")
    
    # Prediction function
    header.append("    /**")
    header.append("     * @brief Predict GFLOPS for given variant configuration")
    header.append("     * ")
    header.append("     * @param features Input features (normalized internally)")
    header.append("     * @return Predicted GFLOPS")
    header.append("     */")
    header.append("    static double predict(const float* features) {")
    header.append("        // Normalize features")
    header.append("        float normalized[NUM_FEATURES];")
    header.append("        for (size_t i = 0; i < NUM_FEATURES; ++i) {")
    header.append("            normalized[i] = (features[i] - SCALER_MEAN[i]) / SCALER_SCALE[i];")
    header.append("        }")
    header.append("")
    
    # Generate forward pass for each layer
    for i, layer in enumerate(layers):
        in_var = "normalized" if i == 0 else f"hidden{i-1}"
        out_var = "output" if i == len(layers) - 1 else f"hidden{i}"
        in_size = layer['weight'].shape[1]
        out_size = layer['weight'].shape[0]
        is_last = (i == len(layers) - 1)
        
        header.append(f"        // Layer {i}")
        header.append(f"        float {out_var}[LAYER{i}_OUT];")
        header.append(f"        for (size_t j = 0; j < LAYER{i}_OUT; ++j) {{")
        header.append(f"            float sum = LAYER{i}_BIAS[j];")
        header.append(f"            for (size_t k = 0; k < LAYER{i}_IN; ++k) {{")
        header.append(f"                sum += LAYER{i}_WEIGHT[j][k] * {in_var}[k];")
        header.append(f"            }}")
        
        if not is_last:
            header.append(f"            {out_var}[j] = std::max(0.0f, sum);  // ReLU")
        else:
            header.append(f"            {out_var}[j] = sum;  // Linear output")
        
        header.append(f"        }}")
        header.append("")
    
    header.append("        return static_cast<double>(output[0]);")
    header.append("    }")
    header.append("")
    
    # Convenience function with individual parameters
    header.append("    /**")
    header.append("     * @brief Predict GFLOPS for given configuration (convenience wrapper)")
    header.append("     */")
    header.append("    static double predict(")
    header.append("        int m, int n, int k,")
    header.append("        int tile_m, int tile_n,")
    header.append("        int unroll_k, int prefetch_dist,")
    header.append("        bool is_avx512")
    header.append("    ) {")
    header.append("        // Compute derived features (must match training script)")
    header.append("        const double problem_size = static_cast<double>(m) * n * k;")
    header.append("        const int tile_area = tile_m * tile_n;")
    header.append("        const double l1_fit_ratio = (tile_area * 4.0) / 32768.0;  // 32KB L1")
    header.append("        const double l2_fit_ratio = (tile_area * 4.0) / 262144.0;  // 256KB L2")
    header.append("        const double m_alignment = static_cast<double>(m % tile_m) / tile_m;")
    header.append("        const double n_alignment = static_cast<double>(n % tile_n) / tile_n;")
    header.append("        const double m_n_ratio = static_cast<double>(m) / n;")
    header.append("        const double tile_bytes = tile_area * 4.0;")
    header.append("        const double working_set_bytes = tile_bytes * (k / unroll_k);")
    header.append("")
    header.append("        float features[NUM_FEATURES] = {")
    header.append("            static_cast<float>(m),")
    header.append("            static_cast<float>(n),")
    header.append("            static_cast<float>(k),")
    header.append("            static_cast<float>(problem_size),")
    header.append("            is_avx512 ? 1.0f : 0.0f,")
    header.append("            static_cast<float>(tile_m),")
    header.append("            static_cast<float>(tile_n),")
    header.append("            static_cast<float>(tile_area),")
    header.append("            static_cast<float>(unroll_k),")
    header.append("            static_cast<float>(prefetch_dist),")
    header.append("            static_cast<float>(l1_fit_ratio),")
    header.append("            static_cast<float>(l2_fit_ratio),")
    header.append("            static_cast<float>(m_alignment),")
    header.append("            static_cast<float>(n_alignment),")
    header.append("            static_cast<float>(m_n_ratio),")
    header.append("            static_cast<float>(tile_bytes),")
    header.append("            static_cast<float>(working_set_bytes),")
    header.append("            static_cast<float>(std::log10(m + 1)),")
    header.append("            static_cast<float>(std::log10(n + 1)),")
    header.append("            static_cast<float>(std::log10(k + 1))")
    header.append("        };")
    header.append("")
    header.append("        return predict(features);")
    header.append("    }")
    header.append("};")
    header.append("")
    header.append("}  // namespace cpu")
    header.append("}  // namespace llaminar")
    
    # Write file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write('\n'.join(header))
        f.write('\n')
    
    print(f"✓ Generated {output_path}")
    print(f"  Size: {output_path.stat().st_size} bytes")
    print(f"  Layers: {len(layers)}")

def main():
    parser = argparse.ArgumentParser(description='Export CPU GEMM heuristic to C++ header')
    parser.add_argument('--model', required=True, help='Path to ONNX model')
    parser.add_argument('--scaler', default='cpu_gemm_scaler.npz', help='Path to scaler params')
    parser.add_argument('--output', default='src/v2/kernels/cpu/CpuGemmHeuristicWeights.h',
                       help='Output header path')
    
    args = parser.parse_args()
    
    # Extract weights
    layers = extract_weights(args.model)
    
    # Load scaler
    scaler_mean, scaler_scale = load_scaler(args.scaler)
    
    # Generate header
    output_path = Path(args.output)
    generate_header(layers, scaler_mean, scaler_scale, output_path)
    
    print(f"\n{'='*70}")
    print(f"Export complete!")
    print(f"  Header: {output_path}")
    print(f"\nNext steps:")
    print(f"  1. Include CpuGemmHeuristicWeights.h in SmartGemmSearch.cpp")
    print(f"  2. Replace scorePerformanceModel() with CpuGemmHeuristic::predict()")
    print(f"  3. Re-run IQ4_NL tests to validate improvement")
    print(f"{'='*70}")

if __name__ == '__main__':
    main()
