#!/usr/bin/env python3
"""
@file generate_gemm_microkernel_instantiations.py
@brief Generate explicit instantiations for all GEMM micro-kernel variants

Generates 64 instantiation files (one per {ISA, MR, NR} combination)
to parallelize compilation across all CPU cores.

Each file instantiates 5 UNROLL_K variants for a specific micro-kernel configuration.

@author David Sanftenberg
"""

import os
import sys
from pathlib import Path
from typing import List, Tuple

# Search space dimensions
ISA_TYPES = ["simd::AVX512Tag", "simd::AVX2Tag"]
MR_VALUES = [1, 2, 4, 8, 16, 32, 64]  # M tile sizes
NR_VALUES = [1, 2, 4, 6, 8, 16, 32, 64]  # N tile sizes
UNROLL_K_VALUES = [1, 2, 4, 8, 16]  # K-loop unroll factors
PREFETCH_DIST_VALUES = [0, 1, 2, 3, 5]  # Prefetch distances

# Output configuration
NUM_FILES = 64
OUTPUT_DIR = Path(__file__).parent / "generated"

def generate_all_combinations() -> List[Tuple[str, int, int, int, int]]:
    """Generate all (ISA, MR, NR, UNROLL_K, PREFETCH_DIST) combinations."""
    combinations = []
    
    for isa in ISA_TYPES:
        for mr in MR_VALUES:
            for nr in NR_VALUES:
                # Skip invalid tile sizes (too large for register file)
                if isa == "simd::AVX512Tag":
                    # AVX512: 32 ZMM registers, need MR*NR + some headroom
                    if mr * nr > 48:  # Conservative limit
                        continue
                else:  # AVX2
                    # AVX2: 16 YMM registers, more constrained
                    if mr * nr > 32:
                        continue
                
                for unroll_k in UNROLL_K_VALUES:
                    for prefetch_dist in PREFETCH_DIST_VALUES:
                        combinations.append((isa, mr, nr, unroll_k, prefetch_dist))
    
    return combinations

def distribute_combinations(combinations: List, num_files: int) -> List[List]:
    """Distribute combinations across files for balanced compilation."""
    num_per_file = len(combinations) // num_files
    remainder = len(combinations) % num_files
    
    distributed = []
    idx = 0
    
    for i in range(num_files):
        count = num_per_file + (1 if i < remainder else 0)
        distributed.append(combinations[idx:idx+count])
        idx += count
    
    return distributed

def generate_file_header(file_index: int) -> str:
    """Generate file header with includes and namespace."""
    return f"""/**
 * @file GemmMicroKernelInstantiations_{file_index:02d}.cpp
 * @brief Explicit template instantiations for GemmMicroKernelTemplate (shard {file_index}/{NUM_FILES})
 *
 * AUTO-GENERATED by generate_gemm_microkernel_instantiations.py
 * DO NOT EDIT MANUALLY
 *
 * @author David Sanftenberg
 * @date October 28, 2025
 */

#include "../fp32/GemmMicroKernelTemplateFP32.h"
#include "../GemmMicroKernelRegistry.h"

namespace llaminar2 {{
namespace kernels {{
namespace gemm {{

// Force-link function to ensure this object file is included
extern "C" void forceLink_GemmMicroKernelInstantiations_{file_index:02d}() {{
    // Empty function - just needs to exist to force linking
}}

// Explicit instantiations (shard {file_index}/{NUM_FILES})

"""

def generate_instantiation(isa: str, mr: int, nr: int, unroll_k: int, prefetch_dist: int) -> str:
    """Generate single explicit instantiation with registration."""
    # Template instantiation (use full namespace)
    inst = f"template class MicroKernelTemplate<{isa}, {mr}, {nr}, {unroll_k}, {prefetch_dist}>;\n"
    
    # For registration, extract just the tag name (AVX512Tag, AVX2Tag)
    isa_tag_only = isa.split("::")[-1]  # "simd::AVX512Tag" -> "AVX512Tag"
    
    # Function-based registration with __attribute__((constructor)) to ensure execution
    reg = f"""namespace {{
    __attribute__((constructor)) void register_{isa_tag_only}_{mr}_{nr}_{unroll_k}_{prefetch_dist}() {{
        using KernelType = MicroKernelTemplate<{isa}, {mr}, {nr}, {unroll_k}, {prefetch_dist}>;
        MicroKernelRegistry::instance().register_kernel(
            "{isa}", {mr}, {nr}, {unroll_k}, {prefetch_dist},
            MicroKernelBundle{{
                &KernelType::micro_kernel,
                &KernelType::pack_A_panel,
                &KernelType::pack_B_panel
            }}
        );
    }}
}}

"""
    
    return inst + reg

def generate_file_footer() -> str:
    """Generate file footer."""
    return """
} // namespace gemm
} // namespace kernels
} // namespace llaminar2
"""

def generate_cmake_fragment(num_files: int) -> str:
    """Generate CMakeLists.txt fragment for including generated files."""
    sources = [f"    kernels/cpu/generated/GemmMicroKernelInstantiations_{i:02d}.cpp" for i in range(num_files)]
    return "\n".join(sources)

def main():
    print("🔧 Generating MicroKernel template instantiations...")
    print(f"   Output: {OUTPUT_DIR}")
    print(f"   Shards: {NUM_FILES}")
    
    # Create output directory
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Generate all combinations
    combinations = generate_all_combinations()
    print(f"   Total combinations: {len(combinations)}")
    
    # Distribute across files
    distributed = distribute_combinations(combinations, NUM_FILES)
    
    # Generate each file
    for file_idx, file_combinations in enumerate(distributed):
        output_path = OUTPUT_DIR / f"GemmMicroKernelInstantiations_{file_idx:02d}.cpp"
        
        with open(output_path, 'w') as f:
            f.write(generate_file_header(file_idx))
            
            for isa, mr, nr, unroll_k, prefetch_dist in file_combinations:
                f.write(generate_instantiation(isa, mr, nr, unroll_k, prefetch_dist))
            
            f.write(generate_file_footer())
        
        print(f"   ✅ Generated {output_path.name} ({len(file_combinations)} instantiations)")
    
    # Generate CMakeLists.txt fragment
    cmake_fragment_path = OUTPUT_DIR / "sources.cmake"
    with open(cmake_fragment_path, 'w') as f:
        f.write("# AUTO-GENERATED by generate_gemm_microkernel_instantiations.py\n")
        f.write("# Include this in src/v2/CMakeLists.txt\n\n")
        f.write("set(MICROKERNEL_INSTANTIATION_SOURCES\n")
        f.write(generate_cmake_fragment(NUM_FILES))
        f.write("\n)\n")
    
    print(f"\n✅ Generated {NUM_FILES} files with {len(combinations)} total instantiations")
    print(f"   CMake fragment: {cmake_fragment_path}")
    print(f"\n📋 Next steps:")
    print(f"   1. Include sources.cmake in src/v2/CMakeLists.txt")
    print(f"   2. Add MICROKERNEL_INSTANTIATION_SOURCES to llaminar2_core target")
    print(f"   3. Build with -j56 for parallel compilation")

if __name__ == "__main__":
    main()
