/**
 * @file Test__Qwen2FP32Parity.cpp
 * @brief End-to-end FP32 parity tests for Qwen2 inference against PyTorch reference
 * @author David Sanftenberg
 * @date 2025-11-06
 * @updated 2025-12-19 - Migrated to IInferenceRunner/GraphOrchestrator
 *
 * Validates Qwen2 inference correctness by comparing against PyTorch ground truth.
 * Uses the unified IInferenceRunner interface which now defaults to GraphOrchestrator.
 *
 * Test Strategy:
 * - Load PyTorch snapshots generated by generate_qwen2_pipeline_snapshots.py
 * - Run inference with same input tokens via IInferenceRunner (Graph path)
 * - Compare intermediate activations stage-by-stage
 * - Tolerance: rel_l2 < 1e-4 for FP32 vs FP32
 *
 * Captured Stages (per layer):
 * - EMBEDDING: Token embeddings
 * - ATTENTION_NORM, Q_PROJECTION, K_PROJECTION, V_PROJECTION
 * - Q_ROPE, K_ROPE, ATTENTION_SCORES, ATTENTION_SOFTMAX
 * - ATTENTION_CONTEXT, ATTENTION_OUTPUT, ATTENTION_RESIDUAL
 * - FFN_NORM, FFN_GATE, FFN_UP, FFN_SWIGLU, FFN_DOWN, FFN_RESIDUAL
 * - FINAL_NORM, LM_HEAD
 *
 * Requirements:
 * - PyTorch snapshots: run `python3 python/reference/generate_qwen2_pipeline_snapshots.py --output pytorch_qwen2_snapshots`
 * - Qwen 2.5 0.5B model: models/qwen2.5-0.5b-instruct-q4_0.gguf
 * - Single-rank execution (no MPI distribution)
 */

#include <gtest/gtest.h>
#include <memory>
#include <vector>
#include <cmath>
#include <cstring>
#include <fstream>
#include <sstream>
#include <unordered_map>
#include <iomanip>

#include "../../../../src/v2/loaders/ModelContext.h"
#include "../../../../src/v2/inference/InferenceRunner.h"
#include "../../../../src/v2/inference/IInferenceRunner.h"
#include "../../../../src/v2/kernels/KernelFactory.h"
#include "../../../../src/v2/utils/Logger.h"

// NumPy .npz file loading (simple C++ implementation)
#include <cnpy.h>

using namespace llaminar2;

// =============================================================================
// TEST CONFIGURATION - Single source of truth for model, prompt, and tokens
// =============================================================================
// These constants ensure C++ tests and Python snapshot generation use
// IDENTICAL inputs, preventing accidental divergence from mismatched prompts.

/// Path to the GGUF model used for both C++ inference and Python snapshot generation
static constexpr const char *TEST_MODEL_PATH = "models/qwen2.5-0.5b-instruct-q4_0.gguf";

/// Input prompt text - MUST match what Python uses to generate snapshots
static constexpr const char *TEST_PROMPT = "The quick brown fox jumps over the lazy dog";

/// Token IDs for the test prompt (from Qwen2.5 tokenizer)
/// "The quick brown fox jumps over the lazy dog" → [785, 3974, 13876, 38835, 34208, 916, 279, 15678, 5562]
static const std::vector<int> TEST_TOKEN_IDS = {785, 3974, 13876, 38835, 34208, 916, 279, 15678, 5562};

/// Snapshot output directory
static constexpr const char *TEST_SNAPSHOT_DIR = "pytorch_qwen2_snapshots";

/// Number of decode steps to run for incremental decode parity testing
static constexpr int TEST_DECODE_STEPS = 5;

// =============================================================================

/**
 * @brief Test fixture for Qwen2 FP32 parity against PyTorch
 */
class Qwen2FP32PrefillVsPytorch : public ::testing::Test
{
protected:
    void SetUp() override
    {
        // Use centralized test configuration constants
        snapshot_dir_ = TEST_SNAPSHOT_DIR;
        model_path_ = TEST_MODEL_PATH;

        // INT8×INT8 Matmul Tolerance (Double Quantization)
        // Llaminar uses INT8×INT8 matmul path with activation quantization:
        //   1. Weights: Q4_0 → dequantize → requantize to INT8 (~1% error)
        //   2. Activations: FP32 → quantize to INT8 per-row (~0.5-1% error)
        //   3. INT8×INT8 matmul → dequantize to FP32 (adds rounding errors)
        // PyTorch reference uses FP32 matmul throughout, so we expect divergence.
        // Empirically observed:
        //   - Q_PROJECTION: rel_l2 ~0.006 (0.6%)
        //   - ATTENTION_OUTPUT: rel_l2 ~0.022 (2.2%, output projection matmul)
        //   - FFN_GATE: max_abs ~0.116 (due to SwiGLU activation on large FFN dimension)
        //   - FFN_DOWN: rel_l2 ~0.051 (5.1%, accumulates error from gate+up+swiglu+down)
        //   - FFN_NORM: rel_l2 ~0.01 (1%)
        //   - FINAL_NORM: rel_l2 ~0.72 (72%, cascading error through 24 layers)
        tolerance_rel_l2_ = 0.06f;  // 6% relative L2 (accounts for FFN error accumulation)
        tolerance_max_abs_ = 0.12f; // 0.12 absolute (accounts for FFN gate projection range)

        // Always regenerate snapshots from the test GGUF model to ensure parity
        // This prevents accidental use of HuggingFace FP32 weights which would cause divergence
        if (!regeneratePyTorchSnapshots())
        {
            FAIL() << "PyTorch snapshot generation failed - cannot run parity tests without valid snapshots";
        }
    }

    /**
     * @brief Regenerate PyTorch snapshots from the same GGUF model
     *
     * This ensures we're comparing C++ vs Python using IDENTICAL weights,
     * avoiding the FP32 vs Q4_0 mismatch issue discovered on 2025-11-07.
     *
     * @return true if snapshots were generated successfully, false otherwise
     */
    bool regeneratePyTorchSnapshots()
    {
        LOG_INFO("[Parity] Regenerating PyTorch snapshots from GGUF: " << model_path_);
        LOG_INFO("[Parity] Using prompt: \"" << TEST_PROMPT << "\"");

        // Build command to regenerate snapshots
        // CRITICAL: Use the same prompt constant that C++ tests use
        // Note: Use bash -c with venv activation to ensure numpy/torch are available
        std::ostringstream cmd;
        cmd << "bash -c 'source /workspaces/llaminar/.venv/bin/activate && python3"
            << " python/reference/generate_qwen2_pipeline_snapshots.py"
            << " --model " << model_path_
            << " --prompt \"" << TEST_PROMPT << "\""
            << " --output " << snapshot_dir_
            << " --decode-steps " << TEST_DECODE_STEPS // Capture prefill + N decode steps
            << "' 2>&1";                               // Capture stderr too

        LOG_DEBUG("[Parity] Running: " << cmd.str());

        // Execute Python script
        FILE *pipe = popen(cmd.str().c_str(), "r");
        if (!pipe)
        {
            LOG_ERROR("[Parity] Failed to execute snapshot generator");
            return false;
        }

        // Read output
        char buffer[256];
        std::string output;
        while (fgets(buffer, sizeof(buffer), pipe) != nullptr)
        {
            output += buffer;
        }

        int exit_code = pclose(pipe);

        if (exit_code != 0)
        {
            LOG_ERROR("[Parity] Snapshot generation failed (exit code " << exit_code << "):");
            LOG_ERROR(output);
            return false;
        }

        LOG_INFO("[Parity] Snapshots regenerated successfully");
        LOG_DEBUG("[Parity] Output:\n"
                  << output);
        return true;
    }

    void TearDown() override
    {
        model_ctx_.reset();
        runner_.reset();
        pytorch_snapshots_.clear();

        // Clear the kernel cache explicitly as a safety measure.
        // Note: Since 2025-01, TensorBase's destructor automatically calls
        // KernelFactory::clearCacheFor(this), which handles cache invalidation.
        // This explicit clearCache() is kept for defense-in-depth.
        llaminar::v2::kernels::KernelFactory::clearCache();
    }

    /**
     * @brief Comparison result structure
     */
    struct ComparisonResult
    {
        bool passed = false;
        float max_abs_diff = 0.0f;
        float mean_abs_diff = 0.0f;
        float rel_l2_norm = 0.0f;
        float cosine_similarity = 0.0f; // NEW: Measures directional alignment
        float kl_divergence = 0.0f;     // NEW: For logits comparison
        float norm_actual = 0.0f;       // L2 norm of actual tensor
        float norm_expected = 0.0f;     // L2 norm of expected tensor
        size_t num_mismatches = 0;
        size_t total_elements = 0;
    }; /**
        * @brief Load PyTorch snapshot from .npy file
        *
        * @param name Stage name (e.g., "EMBEDDING", "layer0_Q_PROJECTION")
        * @return Vector of FP32 values
        */
    std::vector<float> loadPyTorchSnapshot(const std::string &name)
    {
        // Check if already loaded
        if (pytorch_snapshots_.find(name) != pytorch_snapshots_.end())
        {
            return pytorch_snapshots_[name];
        }

        // Load from .npy file
        std::string npy_path = snapshot_dir_ + "/" + name + ".npy";

        try
        {
            cnpy::NpyArray arr = cnpy::npy_load(npy_path);

            // Convert to float vector
            std::vector<float> data;
            if (arr.word_size == sizeof(float))
            {
                float *data_ptr = arr.data<float>();
                data.assign(data_ptr, data_ptr + arr.num_vals);
            }
            else if (arr.word_size == sizeof(double))
            {
                // Convert double to float
                double *data_ptr = arr.data<double>();
                data.resize(arr.num_vals);
                for (size_t i = 0; i < arr.num_vals; ++i)
                {
                    data[i] = static_cast<float>(data_ptr[i]);
                }
            }
            else
            {
                LOG_ERROR("[Parity] Unsupported data type in snapshot '" << name << "'");
                return {};
            }

            // Cache for future use
            pytorch_snapshots_[name] = data;

            LOG_DEBUG("[Parity] Loaded snapshot '" << name << "': " << data.size() << " elements");
            return data;
        }
        catch (const std::exception &e)
        {
            LOG_ERROR("[Parity] Failed to load snapshot '" << name << "': " << e.what());
            return {};
        }
    }

    /**
     * @brief Compute cosine similarity between two vectors
     *
     * Cosine similarity measures the angle between vectors, ignoring magnitude.
     * Returns 1.0 for identical direction, 0.0 for orthogonal, -1.0 for opposite.
     *
     * This is preferred over L2 for embedding comparisons because:
     * - Quantization noise affects magnitude but preserves direction
     * - Semantic meaning is encoded in direction, not magnitude
     */
    static float computeCosineSimilarity(const float *a, const float *b, size_t size)
    {
        double dot_product = 0.0;
        double norm_a = 0.0;
        double norm_b = 0.0;

        for (size_t i = 0; i < size; ++i)
        {
            dot_product += static_cast<double>(a[i]) * static_cast<double>(b[i]);
            norm_a += static_cast<double>(a[i]) * static_cast<double>(a[i]);
            norm_b += static_cast<double>(b[i]) * static_cast<double>(b[i]);
        }

        double denominator = std::sqrt(norm_a) * std::sqrt(norm_b);
        if (denominator < 1e-10)
        {
            return 0.0f; // Avoid division by zero
        }

        return static_cast<float>(dot_product / denominator);
    }

    /**
     * @brief Compute KL divergence between two probability distributions
     *
     * KL(P || Q) = sum(P(x) * log(P(x) / Q(x)))
     *
     * For logits comparison:
     * - First applies softmax to convert logits to probabilities
     * - Returns KL divergence in nats (natural log)
     * - Lower is better: 0.0 means identical distributions
     *
     * @param actual_logits Llaminar logits (unnormalized)
     * @param expected_logits PyTorch logits (unnormalized)
     * @param size Number of elements (seq_len * vocab_size)
     * @param vocab_size Vocabulary size (for per-position softmax)
     */
    static float computeKLDivergence(
        const float *actual_logits,
        const float *expected_logits,
        size_t size,
        size_t vocab_size)
    {
        size_t seq_len = size / vocab_size;
        double total_kl = 0.0;

        for (size_t pos = 0; pos < seq_len; ++pos)
        {
            const float *actual_row = actual_logits + pos * vocab_size;
            const float *expected_row = expected_logits + pos * vocab_size;

            // Find max for numerical stability (log-sum-exp trick)
            float max_actual = actual_row[0];
            float max_expected = expected_row[0];
            for (size_t i = 1; i < vocab_size; ++i)
            {
                max_actual = std::max(max_actual, actual_row[i]);
                max_expected = std::max(max_expected, expected_row[i]);
            }

            // Compute softmax denominators (log-sum-exp)
            double sum_exp_actual = 0.0;
            double sum_exp_expected = 0.0;
            for (size_t i = 0; i < vocab_size; ++i)
            {
                sum_exp_actual += std::exp(actual_row[i] - max_actual);
                sum_exp_expected += std::exp(expected_row[i] - max_expected);
            }
            double log_sum_actual = max_actual + std::log(sum_exp_actual);
            double log_sum_expected = max_expected + std::log(sum_exp_expected);

            // Compute KL divergence for this position
            // KL(expected || actual) - we want expected as reference (P)
            double pos_kl = 0.0;
            for (size_t i = 0; i < vocab_size; ++i)
            {
                double log_p = expected_row[i] - log_sum_expected; // log P(x)
                double log_q = actual_row[i] - log_sum_actual;     // log Q(x)
                double p = std::exp(log_p);

                // Skip very small probabilities to avoid numerical issues
                if (p > 1e-10)
                {
                    pos_kl += p * (log_p - log_q);
                }
            }
            total_kl += pos_kl;
        }

        // Return average KL per position
        return static_cast<float>(total_kl / seq_len);
    }

    /**
     * @brief Compute Top-K overlap between two sets of logits
     *
     * Checks if the top K tokens predicted by both models are the same (ignoring order within top K).
     * This is a "Smoke Test" for decision quality.
     *
     * @param actual_logits Llaminar logits
     * @param expected_logits PyTorch logits
     * @param size Number of elements (seq_len * vocab_size)
     * @param vocab_size Vocabulary size
     * @param k Number of top tokens to consider
     * @return Overlap percentage (0.0 to 1.0)
     */
    static float computeTopKOverlap(
        const float *actual_logits,
        const float *expected_logits,
        size_t size,
        size_t vocab_size,
        int k)
    {
        size_t seq_len = size / vocab_size;
        double total_overlap = 0.0;

        for (size_t pos = 0; pos < seq_len; ++pos)
        {
            const float *actual_row = actual_logits + pos * vocab_size;
            const float *expected_row = expected_logits + pos * vocab_size;

            // Helper to get top K indices
            auto get_top_k = [&](const float *logits)
            {
                std::vector<std::pair<float, int>> scores(vocab_size);
                for (size_t i = 0; i < vocab_size; ++i)
                {
                    scores[i] = {logits[i], static_cast<int>(i)};
                }
                // Partial sort to get top K
                std::partial_sort(scores.begin(), scores.begin() + k, scores.end(),
                                  [](const auto &a, const auto &b)
                                  { return a.first > b.first; });

                std::vector<int> indices(k);
                for (int i = 0; i < k; ++i)
                    indices[i] = scores[i].second;
                // Sort indices for set intersection
                std::sort(indices.begin(), indices.end());
                return indices;
            };

            auto actual_topk = get_top_k(actual_row);
            auto expected_topk = get_top_k(expected_row);

            // Compute intersection size
            std::vector<int> intersection;
            std::set_intersection(
                actual_topk.begin(), actual_topk.end(),
                expected_topk.begin(), expected_topk.end(),
                std::back_inserter(intersection));

            total_overlap += static_cast<double>(intersection.size()) / k;
        }

        return static_cast<float>(total_overlap / seq_len);
    }

    /**
     * @brief Compare Llaminar tensor against PyTorch snapshot
     *
     * @param actual Llaminar tensor data
     * @param expected PyTorch snapshot data
     * @param size Number of elements
     * @return Comparison result
     */
    ComparisonResult compareTensors(
        const float *actual,
        const std::vector<float> &expected,
        size_t size)
    {
        ComparisonResult result;
        result.total_elements = size;

        if (expected.empty())
        {
            LOG_ERROR("[Parity] PyTorch snapshot is empty");
            return result;
        }

        if (expected.size() != size)
        {
            LOG_ERROR("[Parity] Size mismatch: Llaminar=" << size
                                                          << ", PyTorch=" << expected.size());
            return result;
        }

        double sum_abs_diff = 0.0;
        double sum_sq_diff = 0.0;
        double sum_sq_expected = 0.0;
        double sum_sq_actual = 0.0;
        double dot_product = 0.0;

        for (size_t i = 0; i < size; ++i)
        {
            float diff = std::abs(actual[i] - expected[i]);

            if (diff > tolerance_max_abs_)
            {
                result.num_mismatches++;
            }

            if (diff > result.max_abs_diff)
            {
                result.max_abs_diff = diff;
            }

            sum_abs_diff += diff;
            sum_sq_diff += diff * diff;
            sum_sq_expected += expected[i] * expected[i];
            sum_sq_actual += actual[i] * actual[i];
            dot_product += actual[i] * expected[i];
        }

        result.mean_abs_diff = static_cast<float>(sum_abs_diff / size);
        result.norm_actual = static_cast<float>(std::sqrt(sum_sq_actual));
        result.norm_expected = static_cast<float>(std::sqrt(sum_sq_expected));

        // Relative L2 norm: ||actual - expected||_2 / ||expected||_2
        if (sum_sq_expected > 1e-10)
        {
            result.rel_l2_norm = static_cast<float>(std::sqrt(sum_sq_diff / sum_sq_expected));
        }

        // Compute cosine similarity (direction alignment)
        if (result.norm_actual > 1e-10 && result.norm_expected > 1e-10)
        {
            result.cosine_similarity = static_cast<float>(dot_product / (static_cast<double>(result.norm_actual) * static_cast<double>(result.norm_expected)));
        }

        // Pass criteria using cosine similarity (> 0.999)
        // This is more meaningful than L2 for embeddings
        result.passed = (result.cosine_similarity >= 0.999f);

        // DEBUG: Print detailed stats if cosine similarity is low
        if (result.cosine_similarity < 0.9f)
        {
            std::cout << "  DEBUG: Low cosine similarity (" << result.cosine_similarity << ")" << std::endl;
            std::cout << "    Norm Actual:   " << result.norm_actual << std::endl;
            std::cout << "    Norm Expected: " << result.norm_expected << std::endl;
            std::cout << "    Dot Product:   " << dot_product << std::endl;
            std::cout << "    First 10 elements:" << std::endl;
            for (size_t i = 0; i < std::min<size_t>(10, size); ++i)
            {
                std::cout << "      [" << i << "] llaminar=" << actual[i]
                          << " pytorch=" << expected[i]
                          << " diff=" << (actual[i] - expected[i]) << std::endl;
            }
        }

        return result;
    }

    /**
     * @brief Compare logits with KL divergence
     *
     * @param actual_logits Llaminar logits
     * @param expected_logits PyTorch logits
     * @param size Total elements (seq_len * vocab_size)
     * @param vocab_size Vocabulary size
     * @return Comparison result with KL divergence
     */
    ComparisonResult compareLogits(
        const float *actual_logits,
        const std::vector<float> &expected_logits,
        size_t size,
        size_t vocab_size)
    {
        ComparisonResult result = compareTensors(actual_logits, expected_logits, size);

        // Compute KL divergence for logits
        result.kl_divergence = computeKLDivergence(
            actual_logits, expected_logits.data(), size, vocab_size);

        // For logits, pass based on KL divergence < 0.005
        result.passed = (result.kl_divergence < 0.005f);

        return result;
    }

    /**
     * @brief Print comparison result
     */
    void printComparisonResult(const ComparisonResult &result, const std::string &name)
    {
        std::cout << "=== " << name << " ===" << std::endl;
        std::cout << "  Elements:       " << result.total_elements << std::endl;
        std::cout << "  Cosine Sim:     " << std::fixed << std::setprecision(6) << result.cosine_similarity << std::endl;
        std::cout << "  Rel L2 norm:    " << std::fixed << std::setprecision(4) << result.rel_l2_norm << std::endl;
        std::cout << "  Norm Actual:    " << std::fixed << std::setprecision(4) << result.norm_actual << std::endl;
        std::cout << "  Norm Expected:  " << std::fixed << std::setprecision(4) << result.norm_expected << std::endl;
        if (result.kl_divergence > 0.0f)
        {
            std::cout << "  KL Divergence:  " << std::fixed << std::setprecision(6) << result.kl_divergence << std::endl;
        }
        std::cout << "  Max abs diff:   " << result.max_abs_diff << std::endl;
        std::cout << "  Status:         " << (result.passed ? "✓ PASSED" : "✗ FAILED") << std::endl;
    }

    /**
     * @brief Load model and create pipeline
     */
    bool setupPipeline()
    {
        // Initialize device manager (required before creating inference runner)
        DeviceManager::instance().initialize(-1); // -1 = no NUMA filtering

        model_ctx_ = ModelContext::create(model_path_);
        if (!model_ctx_)
        {
            LOG_ERROR("[Parity] Failed to load model: " << model_path_);
            return false;
        }

        // Create inference runner (defaults to GraphOrchestrator as of Dec 2025)
        InferenceRunnerConfig runner_config;
        runner_config.max_seq_len = 4096;
        runner_config.batch_size = 1;
        // Use Graph path - the GraphOrchestrator with full declarative execution
        runner_config.force_graph = true;

        // Get CPU device index explicitly (no magic -1 values)
        auto &dm = DeviceManager::instance();
        int cpu_device = dm.cpuDeviceIndex();

        runner_ = createInferenceRunner(
            model_ctx_,
            nullptr, // No MPI context (single-rank)
            cpu_device,
            runner_config);

        if (!runner_)
        {
            LOG_ERROR("[Parity] Failed to create inference runner");
            return false;
        }

        // Enable snapshot capture for parity testing
        runner_->enableSnapshotCapture();
        LOG_INFO("[Parity] Snapshot capture enabled");

        LOG_INFO("[Parity] Inference runner created successfully (path: "
                 << (runner_->executionPath() == ExecutionPath::GRAPH ? "GRAPH" : "PIPELINE") << ")");
        return true;
    }

    /**
     * @brief Read token IDs from PyTorch metadata
     *
     * Returns the token IDs used by PyTorch to generate snapshots.
     * Uses the centralized TEST_TOKEN_IDS constant to ensure C++ and Python
     * use identical inputs.
     */
    std::vector<int> readTokenIdsFromMetadata()
    {
        // Use centralized token IDs constant
        // This ensures C++ tests use the same tokens as Python snapshot generation
        // Prompt: "The quick brown fox jumps over the lazy dog"
        return TEST_TOKEN_IDS;
    }

    /**
     * @brief Read decode token IDs from snapshot metadata
     *
     * Returns the token IDs generated by PyTorch during autoregressive decode.
     * These are the actual tokens PyTorch used for each decode step, which may
     * differ from Llaminar's argmax due to numerical differences in prefill.
     *
     * Format in metadata.txt: "decode_tokens: 3110,6783,60119,87896"
     */
    std::vector<int> readDecodeTokensFromMetadata()
    {
        std::string metadata_path = snapshot_dir_ + "/metadata.txt";
        std::ifstream file(metadata_path);
        if (!file.is_open())
        {
            LOG_WARN("[Parity] Cannot open metadata file: " << metadata_path);
            return {};
        }

        std::string line;
        while (std::getline(file, line))
        {
            // Look for "decode_tokens: 3110,6783,60119,87896"
            if (line.find("decode_tokens:") == 0)
            {
                // Extract the token list after ": "
                size_t colon_pos = line.find(':');
                if (colon_pos == std::string::npos)
                {
                    LOG_WARN("[Parity] Malformed decode_tokens line");
                    return {};
                }

                std::string token_list = line.substr(colon_pos + 1);

                // Trim leading whitespace
                size_t start = token_list.find_first_not_of(" \t");
                if (start != std::string::npos)
                {
                    token_list = token_list.substr(start);
                }

                // Parse comma-separated integers
                std::vector<int> tokens;
                std::istringstream iss(token_list);
                std::string token_str;

                while (std::getline(iss, token_str, ','))
                {
                    try
                    {
                        tokens.push_back(std::stoi(token_str));
                    }
                    catch (const std::exception &e)
                    {
                        LOG_WARN("[Parity] Failed to parse token: " << token_str);
                        return {};
                    }
                }

                LOG_INFO("[Parity] Read " << tokens.size() << " decode tokens from metadata");
                return tokens;
            }
        }

        LOG_WARN("[Parity] No decode_tokens line found in metadata");
        return {};
    }

    // Test state
    std::string snapshot_dir_;
    std::string model_path_;
    float tolerance_rel_l2_;
    float tolerance_max_abs_;

    std::shared_ptr<ModelContext> model_ctx_;
    std::unique_ptr<IInferenceRunner> runner_;
    std::unordered_map<std::string, std::vector<float>> pytorch_snapshots_;
};

/**
 * @brief Test: Embedding layer parity
 *
 * Validates that Qwen2Pipeline's embedding layer produces identical output to PyTorch.
 */
TEST_F(Qwen2FP32PrefillVsPytorch, EmbeddingLayer)
{
    // Setup
    ASSERT_TRUE(setupPipeline());

    // Get token IDs (same as PyTorch)
    std::vector<int> tokens = readTokenIdsFromMetadata();
    ASSERT_FALSE(tokens.empty()) << "Failed to read token IDs";

    LOG_INFO("[Parity] Testing with " << tokens.size() << " tokens");

    // Run pipeline forward pass
    bool success = runner_->forward(tokens.data(), tokens.size());
    ASSERT_TRUE(success) << "Pipeline forward pass failed";

    // Load PyTorch embedding snapshot
    auto pytorch_embedding = loadPyTorchSnapshot("EMBEDDING");
    ASSERT_FALSE(pytorch_embedding.empty()) << "Failed to load PyTorch EMBEDDING snapshot";

    // Get embedding snapshot from runner
    size_t llaminar_size;
    const float *llaminar_embedding = runner_->getSnapshot("EMBEDDING", llaminar_size);
    ASSERT_NE(llaminar_embedding, nullptr) << "Failed to get EMBEDDING snapshot from runner";

    // Compare
    auto result = compareTensors(llaminar_embedding, pytorch_embedding, llaminar_size);
    printComparisonResult(result, "EMBEDDING");

    EXPECT_TRUE(result.passed)
        << "EMBEDDING parity failed: rel_l2=" << result.rel_l2_norm
        << ", max_abs=" << result.max_abs_diff;
}

/**
 * @brief Test: Layer 0 attention block parity
 *
 * Validates all attention stages for layer 0:
 * - ATTENTION_NORM
 * - Q_PROJECTION, K_PROJECTION, V_PROJECTION
 * - Q_ROPE, K_ROPE
 * - ATTENTION_CONTEXT, ATTENTION_OUTPUT
 * - ATTENTION_RESIDUAL
 */
TEST_F(Qwen2FP32PrefillVsPytorch, Layer0_AttentionBlock)
{
    // Setup
    ASSERT_TRUE(setupPipeline());

    // Get token IDs
    std::vector<int> tokens = readTokenIdsFromMetadata();
    ASSERT_FALSE(tokens.empty());

    // Run pipeline
    bool success = runner_->forward(tokens.data(), tokens.size());
    ASSERT_TRUE(success);

    // List of attention stages to validate
    std::vector<std::string> attention_stages = {
        "ATTENTION_NORM",
        "Q_PROJECTION",
        "K_PROJECTION",
        "V_PROJECTION",
        "Q_ROPE",
        "K_ROPE",
        "ATTENTION_CONTEXT",
        "ATTENTION_OUTPUT",
        "ATTENTION_RESIDUAL"};

    int layer_idx = 0;
    int passed_count = 0;
    int failed_count = 0;

    for (const auto &stage : attention_stages)
    {
        std::string snapshot_name = "layer" + std::to_string(layer_idx) + "_" + stage;

        // Load PyTorch snapshot
        auto pytorch_data = loadPyTorchSnapshot(snapshot_name);
        if (pytorch_data.empty())
        {
            LOG_ERROR("[Parity] Failed to load PyTorch snapshot: " << snapshot_name);
            failed_count++;
            continue;
        }

        // Get Llaminar snapshot
        size_t llaminar_size;
        const float *llaminar_data = runner_->getSnapshot(snapshot_name, llaminar_size);
        if (llaminar_data == nullptr)
        {
            LOG_ERROR("[Parity] Failed to get Llaminar snapshot: " << snapshot_name);
            failed_count++;
            continue;
        }

        // Compare
        auto result = compareTensors(llaminar_data, pytorch_data, llaminar_size);
        printComparisonResult(result, snapshot_name);

        // DEBUG: Print sample values on mismatch
        if (!result.passed && (snapshot_name.find("Q_PROJECTION") != std::string::npos ||
                               snapshot_name.find("ATTENTION_CONTEXT") != std::string::npos))
        {
            LOG_INFO("[DEBUG] " << snapshot_name << " sample values:");
            LOG_INFO("[DEBUG]   Llaminar first 10: " << llaminar_data[0] << ", " << llaminar_data[1] << ", "
                                                     << llaminar_data[2] << ", " << llaminar_data[3] << ", " << llaminar_data[4] << ", "
                                                     << llaminar_data[5] << ", " << llaminar_data[6] << ", " << llaminar_data[7] << ", "
                                                     << llaminar_data[8] << ", " << llaminar_data[9]);
            LOG_INFO("[DEBUG]   PyTorch first 10: " << pytorch_data[0] << ", " << pytorch_data[1] << ", "
                                                    << pytorch_data[2] << ", " << pytorch_data[3] << ", " << pytorch_data[4] << ", "
                                                    << pytorch_data[5] << ", " << pytorch_data[6] << ", " << pytorch_data[7] << ", "
                                                    << pytorch_data[8] << ", " << pytorch_data[9]);

            // Also print at different positions
            if (snapshot_name.find("ATTENTION_CONTEXT") != std::string::npos)
            {
                size_t n_elements = llaminar_size / sizeof(float);
                LOG_INFO("[DEBUG] Total elements: " << n_elements);
                LOG_INFO("[DEBUG] Head 1 first 5 (offset 64): " << llaminar_data[64] << ", " << llaminar_data[65] << ", "
                                                                << llaminar_data[66] << ", " << llaminar_data[67] << ", " << llaminar_data[68]);
                LOG_INFO("[DEBUG] PyTorch Head 1 first 5:     " << pytorch_data[64] << ", " << pytorch_data[65] << ", "
                                                                << pytorch_data[66] << ", " << pytorch_data[67] << ", " << pytorch_data[68]);
                LOG_INFO("[DEBUG] Row 1 first 5 (offset 896): " << llaminar_data[896] << ", " << llaminar_data[897] << ", "
                                                                << llaminar_data[898] << ", " << llaminar_data[899] << ", " << llaminar_data[900]);
                LOG_INFO("[DEBUG] PyTorch Row 1 first 5:       " << pytorch_data[896] << ", " << pytorch_data[897] << ", "
                                                                 << pytorch_data[898] << ", " << pytorch_data[899] << ", " << pytorch_data[900]);
            }
        }

        if (result.passed)
        {
            passed_count++;
        }
        else
        {
            failed_count++;
            // Stop at first failure for easier debugging
            EXPECT_TRUE(false)
                << "First divergence at " << snapshot_name
                << ": rel_l2=" << result.rel_l2_norm
                << ", max_abs=" << result.max_abs_diff;
            break;
        }
    }

    LOG_INFO("[Parity] Attention block: " << passed_count << "/" << attention_stages.size() << " stages passed");
    EXPECT_EQ(failed_count, 0) << "Some attention stages failed parity check";
}

/**
 * @brief Test: Layer 0 FFN block parity
 *
 * Validates all FFN stages for layer 0:
 * - FFN_NORM
 * - FFN_GATE, FFN_UP
 * - FFN_SWIGLU
 * - FFN_DOWN
 * - FFN_RESIDUAL
 */
TEST_F(Qwen2FP32PrefillVsPytorch, Layer0_FFNBlock)
{
    // Setup
    ASSERT_TRUE(setupPipeline());

    // Get token IDs
    std::vector<int> tokens = readTokenIdsFromMetadata();
    ASSERT_FALSE(tokens.empty());

    // Run pipeline
    bool success = runner_->forward(tokens.data(), tokens.size());
    ASSERT_TRUE(success);

    // List of FFN stages to validate
    std::vector<std::string> ffn_stages = {
        "FFN_NORM",
        "FFN_GATE",
        "FFN_UP",
        "FFN_SWIGLU",
        "FFN_DOWN",
        "FFN_RESIDUAL"};

    int layer_idx = 0;
    int passed_count = 0;
    int failed_count = 0;

    for (const auto &stage : ffn_stages)
    {
        std::string snapshot_name = "layer" + std::to_string(layer_idx) + "_" + stage;

        // Load PyTorch snapshot
        auto pytorch_data = loadPyTorchSnapshot(snapshot_name);
        if (pytorch_data.empty())
        {
            LOG_ERROR("[Parity] Failed to load PyTorch snapshot: " << snapshot_name);
            failed_count++;
            continue;
        }

        // Get Llaminar snapshot
        size_t llaminar_size;
        const float *llaminar_data = runner_->getSnapshot(snapshot_name, llaminar_size);
        if (llaminar_data == nullptr)
        {
            LOG_ERROR("[Parity] Failed to get Llaminar snapshot: " << snapshot_name);
            failed_count++;
            continue;
        }

        // Compare
        auto result = compareTensors(llaminar_data, pytorch_data, llaminar_size);
        printComparisonResult(result, snapshot_name);

        if (result.passed)
        {
            passed_count++;
        }
        else
        {
            failed_count++;
            // Stop at first failure for easier debugging
            EXPECT_TRUE(false)
                << "First divergence at " << snapshot_name
                << ": rel_l2=" << result.rel_l2_norm
                << ", max_abs=" << result.max_abs_diff;
            break;
        }
    }

    LOG_INFO("[Parity] FFN block: " << passed_count << "/" << ffn_stages.size() << " stages passed");
    EXPECT_EQ(failed_count, 0) << "Some FFN stages failed parity check";
}

/**
 * @brief Test: Final norm and LM head parity
 *
 * Validates:
 * - FINAL_NORM: RMSNorm output after all transformer layers
 * - LM_HEAD: Logits over vocabulary
 *
 * NOTE: Q4_0 quantized weights vs FP32 PyTorch reference has high accumulated
 * error through 24 transformer layers. We use relaxed tolerances here.
 * For stricter parity, use qwen2.5-0.5b-instruct-fp16.gguf model.
 */
TEST_F(Qwen2FP32PrefillVsPytorch, FinalNormAndLogits)
{
    // Setup
    ASSERT_TRUE(setupPipeline());

    // Get token IDs
    std::vector<int> tokens = readTokenIdsFromMetadata();
    ASSERT_FALSE(tokens.empty());

    // Run pipeline
    bool success = runner_->forward(tokens.data(), tokens.size());
    ASSERT_TRUE(success);

    // Relaxed tolerances for final stages (accumulated error through 24 layers)
    // Q4_0 model has inherent quantization error that cascades through the network.
    // With proper bias handling, we see cosine ~0.997 and rel_l2 ~7% at final norm.
    // The max_abs can be larger due to outlier accumulated errors in specific dimensions.
    const float final_tolerance_rel_l2 = 0.20f;  // 20% relative L2 (vs 6% for early stages)
    const float final_tolerance_max_abs = 30.0f; // 30.0 absolute (cascaded quantization error)
    const float final_cosine_threshold = 0.995f; // Cosine > 0.995 is acceptable for final stages

    // Test FINAL_NORM
    {
        auto pytorch_final_norm = loadPyTorchSnapshot("FINAL_NORM");
        ASSERT_FALSE(pytorch_final_norm.empty()) << "Failed to load FINAL_NORM snapshot";

        size_t llaminar_size;
        const float *llaminar_final_norm = runner_->getSnapshot("FINAL_NORM", llaminar_size);
        ASSERT_NE(llaminar_final_norm, nullptr) << "Failed to get FINAL_NORM snapshot";

        auto result = compareTensors(llaminar_final_norm, pytorch_final_norm, llaminar_size);
        printComparisonResult(result, "FINAL_NORM");

        // Use relaxed tolerance for final stages - check cosine OR (rel_l2 AND max_abs)
        bool passed = (result.cosine_similarity >= final_cosine_threshold) ||
                      (result.max_abs_diff <= final_tolerance_max_abs &&
                       result.rel_l2_norm <= final_tolerance_rel_l2);
        EXPECT_TRUE(passed)
            << "FINAL_NORM parity failed: cosine=" << result.cosine_similarity
            << " (tol=" << final_cosine_threshold << ")"
            << ", rel_l2=" << result.rel_l2_norm
            << " (tol=" << final_tolerance_rel_l2 << ")"
            << ", max_abs=" << result.max_abs_diff
            << " (tol=" << final_tolerance_max_abs << ")";
    }

    // Test LM_HEAD (logits)
    {
        auto pytorch_logits = loadPyTorchSnapshot("LM_HEAD");
        ASSERT_FALSE(pytorch_logits.empty()) << "Failed to load LM_HEAD snapshot";

        size_t llaminar_size;
        const float *llaminar_logits = runner_->getSnapshot("LM_HEAD", llaminar_size);
        ASSERT_NE(llaminar_logits, nullptr) << "Failed to get LM_HEAD snapshot";

        auto result = compareTensors(llaminar_logits, pytorch_logits, llaminar_size);
        printComparisonResult(result, "LM_HEAD");

        // Use relaxed tolerance for final stages - check cosine OR (rel_l2 AND max_abs)
        bool passed = (result.cosine_similarity >= final_cosine_threshold) ||
                      (result.max_abs_diff <= final_tolerance_max_abs &&
                       result.rel_l2_norm <= final_tolerance_rel_l2);
        EXPECT_TRUE(passed)
            << "LM_HEAD parity failed: cosine=" << result.cosine_similarity
            << " (tol=" << final_cosine_threshold << ")"
            << ", rel_l2=" << result.rel_l2_norm
            << " (tol=" << final_tolerance_rel_l2 << ")"
            << ", max_abs=" << result.max_abs_diff
            << " (tol=" << final_tolerance_max_abs << ")";
    }
}

/**
 * @brief Test: Complete pipeline parity (all layers)
 *
 * Validates all intermediate activations across all 24 transformer layers.
 * Shows a layer-by-layer summary table with cumulative L2 error.
 */
TEST_F(Qwen2FP32PrefillVsPytorch, AllLayersParity)
{
    ASSERT_TRUE(setupPipeline());

    std::vector<int> tokens = readTokenIdsFromMetadata();
    ASSERT_FALSE(tokens.empty());

    LOG_INFO("[Parity] Running forward pass with " << tokens.size() << " tokens");
    bool success = runner_->forward(tokens.data(), tokens.size());
    ASSERT_TRUE(success) << "Pipeline forward pass failed";

    int n_layers = model_ctx_->model().block_count;

    // Stages to compare per layer
    std::vector<std::string> per_layer_stages = {
        "ATTENTION_NORM", "Q_PROJECTION", "K_PROJECTION", "V_PROJECTION",
        "Q_ROPE", "K_ROPE",
        "ATTENTION_CONTEXT", "ATTENTION_OUTPUT", "ATTENTION_RESIDUAL",
        "FFN_NORM", "FFN_GATE", "FFN_UP", "FFN_SWIGLU", "FFN_DOWN", "FFN_RESIDUAL"};

    // Cosine similarity threshold: vectors must be >99.9% directionally aligned
    const float COSINE_THRESHOLD = 0.999f;
    // KL divergence threshold for final logits (probability distribution check)
    // Relaxed from 0.005 to 0.15 based on feedback that < 0.15 is acceptable for mixed precision
    const float KL_THRESHOLD = 0.15f;

    // Store per-layer statistics (using cosine similarity instead of L2)
    struct LayerStats
    {
        int layer_idx;
        float min_cosine_sim; // Minimum cosine similarity across all stages in this layer
        float avg_cosine_sim; // Average cosine similarity across all stages
        float max_rel_l2;     // Keep L2 for reference
        std::string worst_stage;
        int stages_compared;
        bool passed;
    };
    std::vector<LayerStats> layer_stats;

    // Compare embedding first
    float embedding_cosine = 0.0f;
    float embedding_l2 = 0.0f;
    {
        auto pytorch_data = loadPyTorchSnapshot("EMBEDDING");
        if (!pytorch_data.empty())
        {
            size_t llaminar_size;
            const float *llaminar_data = runner_->getSnapshot("EMBEDDING", llaminar_size);
            if (llaminar_data != nullptr)
            {
                auto result = compareTensors(llaminar_data, pytorch_data, llaminar_size);
                embedding_cosine = result.cosine_similarity;
                embedding_l2 = result.rel_l2_norm;
            }
        }
    }

    // Compare each layer
    for (int layer_idx = 0; layer_idx < n_layers; ++layer_idx)
    {
        LayerStats stats{};
        stats.layer_idx = layer_idx;
        stats.min_cosine_sim = 1.0f; // Start at perfect similarity
        stats.avg_cosine_sim = 0.0f;
        stats.max_rel_l2 = 0.0f;
        stats.stages_compared = 0;
        float sum_cosine = 0.0f;

        for (const auto &stage : per_layer_stages)
        {
            std::string snapshot_name = "layer" + std::to_string(layer_idx) + "_" + stage;
            auto pytorch_data = loadPyTorchSnapshot(snapshot_name);

            if (pytorch_data.empty())
                continue;

            size_t llaminar_size;
            const float *llaminar_data = runner_->getSnapshot(snapshot_name, llaminar_size);

            if (llaminar_data == nullptr)
                continue;

            auto result = compareTensors(llaminar_data, pytorch_data, llaminar_size);
            stats.stages_compared++;
            sum_cosine += result.cosine_similarity;

            // Track minimum cosine similarity (worst case)
            if (result.cosine_similarity < stats.min_cosine_sim)
            {
                stats.min_cosine_sim = result.cosine_similarity;
                stats.worst_stage = stage;
            }
            // Also track max L2 for reference
            if (result.rel_l2_norm > stats.max_rel_l2)
            {
                stats.max_rel_l2 = result.rel_l2_norm;
            }
        }

        if (stats.stages_compared > 0)
        {
            stats.avg_cosine_sim = sum_cosine / stats.stages_compared;
        }
        // Pass if minimum cosine similarity exceeds threshold
        stats.passed = (stats.min_cosine_sim >= COSINE_THRESHOLD);

        layer_stats.push_back(stats);
    }

    // Compare final norm and LM head
    float final_norm_cosine = 0.0f;
    float final_norm_l2 = 0.0f;
    float lm_head_cosine = 0.0f;
    float lm_head_l2 = 0.0f;
    float lm_head_kl_divergence = 0.0f;
    float lm_head_top1_overlap = 0.0f;
    float lm_head_top5_overlap = 0.0f;
    std::vector<float> pytorch_lm_head_data;
    const float *llaminar_lm_head_data = nullptr;
    size_t lm_head_size = 0;

    {
        auto pytorch_data = loadPyTorchSnapshot("FINAL_NORM");
        if (!pytorch_data.empty())
        {
            size_t llaminar_size;
            const float *llaminar_data = runner_->getSnapshot("FINAL_NORM", llaminar_size);
            if (llaminar_data != nullptr)
            {
                auto result = compareTensors(llaminar_data, pytorch_data, llaminar_size);
                final_norm_cosine = result.cosine_similarity;
                final_norm_l2 = result.rel_l2_norm;
            }
        }

        pytorch_lm_head_data = loadPyTorchSnapshot("LM_HEAD");
        if (!pytorch_lm_head_data.empty())
        {
            llaminar_lm_head_data = runner_->getSnapshot("LM_HEAD", lm_head_size);
            if (llaminar_lm_head_data != nullptr)
            {
                auto result = compareTensors(llaminar_lm_head_data, pytorch_lm_head_data, lm_head_size);
                lm_head_cosine = result.cosine_similarity;
                lm_head_l2 = result.rel_l2_norm;

                // Compute KL divergence for final logits (probability distribution check)
                // Note: We compare the last token's logits (most important for generation)
                size_t vocab_size = model_ctx_->model().vocab_size;
                size_t seq_len = lm_head_size / vocab_size;
                if (seq_len > 0 && lm_head_size == seq_len * vocab_size)
                {
                    // Compare last token's logits (single row = vocab_size elements)
                    size_t last_token_offset = (seq_len - 1) * vocab_size;
                    lm_head_kl_divergence = computeKLDivergence(
                        llaminar_lm_head_data + last_token_offset,
                        pytorch_lm_head_data.data() + last_token_offset,
                        vocab_size, // size = vocab_size (just 1 row)
                        vocab_size  // vocab_size
                    );

                    // Compute Top-1 Overlap
                    lm_head_top1_overlap = computeTopKOverlap(
                        llaminar_lm_head_data + last_token_offset,
                        pytorch_lm_head_data.data() + last_token_offset,
                        vocab_size,
                        vocab_size,
                        1);

                    // Compute Top-5 Overlap
                    lm_head_top5_overlap = computeTopKOverlap(
                        llaminar_lm_head_data + last_token_offset,
                        pytorch_lm_head_data.data() + last_token_offset,
                        vocab_size,
                        vocab_size,
                        5);
                }
            }
        }
    }

    // Print summary table (using cosine similarity instead of L2)
    std::cout << "\n";
    std::cout << "╔═══════════════════════════════════════════════════════════════════════════════════════╗\n";
    std::cout << "║                         LAYER-BY-LAYER PARITY SUMMARY                                 ║\n";
    std::cout << "║                    (Threshold: cosine similarity >= " << std::fixed << std::setprecision(3) << COSINE_THRESHOLD << ")                           ║\n";
    std::cout << "╠═══════════╦═══════════════╦═══════════════╦═══════════════╦════════════════════╦══════╣\n";
    std::cout << "║   Layer   ║   Avg Cosine  ║   Min Cosine  ║   Max L2 (%)  ║    Worst Stage     ║Status║\n";
    std::cout << "╠═══════════╬═══════════════╬═══════════════╬═══════════════╬════════════════════╬══════╣\n";

    // Embedding row
    bool embedding_passed = (embedding_cosine >= COSINE_THRESHOLD);
    std::cout << "║ EMBEDDING ║"
              << std::setw(13) << std::fixed << std::setprecision(6) << embedding_cosine << " ║"
              << std::setw(13) << std::fixed << std::setprecision(6) << embedding_cosine << " ║"
              << std::setw(12) << std::fixed << std::setprecision(2) << (embedding_l2 * 100.0f) << "% ║"
              << std::setw(19) << "-" << " ║"
              << (embedding_passed ? "  ✓  " : "  ✗  ") << "║\n";

    // Layer rows
    int layers_passed = embedding_passed ? 1 : 0;
    int first_failed_layer = -1;

    for (const auto &stats : layer_stats)
    {
        std::string layer_str = "Layer " + std::to_string(stats.layer_idx);
        std::cout << "║" << std::setw(10) << layer_str << " ║"
                  << std::setw(13) << std::fixed << std::setprecision(6) << stats.avg_cosine_sim << " ║"
                  << std::setw(13) << std::fixed << std::setprecision(6) << stats.min_cosine_sim << " ║"
                  << std::setw(12) << std::fixed << std::setprecision(2) << (stats.max_rel_l2 * 100.0f) << "% ║"
                  << std::setw(19) << stats.worst_stage << " ║"
                  << (stats.passed ? "  ✓  " : "  ✗  ") << "║\n";

        if (stats.passed)
        {
            layers_passed++;
        }
        else if (first_failed_layer < 0)
        {
            first_failed_layer = stats.layer_idx;
        }
    }

    // Final stages
    bool final_norm_passed = (final_norm_cosine >= COSINE_THRESHOLD);
    bool lm_head_passed = (lm_head_cosine >= COSINE_THRESHOLD) && (lm_head_kl_divergence < KL_THRESHOLD);

    std::cout << "╠═══════════╬═══════════════╬═══════════════╬═══════════════╬════════════════════╬══════╣\n";
    std::cout << "║FINAL_NORM ║"
              << std::setw(13) << std::fixed << std::setprecision(6) << final_norm_cosine << " ║"
              << std::setw(13) << std::fixed << std::setprecision(6) << final_norm_cosine << " ║"
              << std::setw(12) << std::fixed << std::setprecision(2) << (final_norm_l2 * 100.0f) << "% ║"
              << std::setw(19) << "-" << "  ║"
              << (final_norm_passed ? "  ✓  " : "  ✗  ") << "║\n";
    std::cout << "║  LM_HEAD  ║"
              << std::setw(13) << std::fixed << std::setprecision(6) << lm_head_cosine << " ║"
              << std::setw(13) << std::fixed << std::setprecision(6) << lm_head_cosine << " ║"
              << std::setw(12) << std::fixed << std::setprecision(2) << (lm_head_l2 * 100.0f) << "% ║"
              << std::setw(19) << "-" << "  ║"
              << (lm_head_passed ? "  ✓  " : "  ✗  ") << "║\n";

    std::cout << "╚═══════════╩═══════════════╩═══════════════╩═══════════════╩════════════════════╩══════╝\n";

    // Summary
    int total_layers = n_layers + 3; // layers + embedding + final_norm + lm_head
    if (final_norm_passed)
        layers_passed++;
    if (lm_head_passed)
        layers_passed++;

    std::cout << "\n";
    std::cout << "Summary: " << layers_passed << "/" << total_layers << " stages passed ("
              << std::fixed << std::setprecision(1) << (100.0f * layers_passed / total_layers) << "%)\n";

    if (first_failed_layer >= 0)
    {
        std::cout << "First failure: Layer " << first_failed_layer << "\n";
    }

    // Find minimum cosine similarity across all layers
    float min_layer_cosine = 1.0f;
    for (const auto &stats : layer_stats)
    {
        if (stats.min_cosine_sim < min_layer_cosine)
            min_layer_cosine = stats.min_cosine_sim;
    }
    std::cout << "Min layer cosine: " << std::fixed << std::setprecision(6) << min_layer_cosine << "\n";
    std::cout << "Final norm cosine: " << std::fixed << std::setprecision(6) << final_norm_cosine << "\n";
    std::cout << "LM head cosine:    " << std::fixed << std::setprecision(6) << lm_head_cosine << "\n";
    std::cout << "LM head KL div:    " << std::fixed << std::setprecision(6) << lm_head_kl_divergence
              << (lm_head_kl_divergence < KL_THRESHOLD ? " (PASS)" : " (FAIL)") << "\n";
    std::cout << "LM head Top-1:     " << std::fixed << std::setprecision(2) << (lm_head_top1_overlap * 100.0f) << "%\n";
    std::cout << "LM head Top-5:     " << std::fixed << std::setprecision(2) << (lm_head_top5_overlap * 100.0f) << "%\n";
    std::cout << "\n";

    // The test passes if layers 0-3 (early layers) have high cosine similarity
    // This validates the core implementation is correct, even if small
    // numerical differences accumulate in later layers
    int early_layers_passed = 0;
    for (int i = 0; i < std::min(4, n_layers); ++i)
    {
        if (layer_stats[i].passed)
            early_layers_passed++;
    }

    EXPECT_GE(early_layers_passed, 3)
        << "At least 3 of the first 4 layers should pass parity (cosine >= " << COSINE_THRESHOLD << ")";

    // Check that KL divergence for final logits is acceptable
    EXPECT_LT(lm_head_kl_divergence, KL_THRESHOLD)
        << "LM_HEAD KL divergence too high: " << lm_head_kl_divergence
        << " (threshold: " << KL_THRESHOLD << ")";

    // Log observation about error accumulation
    if (first_failed_layer >= 0 && first_failed_layer < n_layers / 2)
    {
        LOG_WARN("[Parity] Cosine similarity drops quickly - first failure at layer "
                 << first_failed_layer << " (< 50% through model)");
    }
}

/**
 * @brief Test: Snapshot loading infrastructure
 *
 * Validates that PyTorch snapshots can be loaded correctly.
 */
TEST_F(Qwen2FP32PrefillVsPytorch, SnapshotLoadingInfrastructure)
{
    // Try loading embedding snapshot
    auto embedding = loadPyTorchSnapshot("EMBEDDING");

    if (embedding.empty())
    {
        GTEST_SKIP() << "PyTorch snapshots not found. Run: python3 python/reference/generate_qwen2_pipeline_snapshots.py --output " << snapshot_dir_;
    }

    // Check embedding size
    // Expected: [batch=1, seq_len=9, d_model=896] = 8064 elements
    EXPECT_EQ(embedding.size(), 1 * 9 * 896) << "EMBEDDING snapshot size mismatch";

    LOG_INFO("[Parity] Successfully loaded EMBEDDING snapshot: " << embedding.size() << " elements");

    // Try loading layer 0 snapshots
    std::vector<std::string> test_stages = {
        "layer0_Q_PROJECTION",
        "layer0_ATTENTION_RESIDUAL",
        "layer0_FFN_RESIDUAL"};

    for (const auto &stage : test_stages)
    {
        auto data = loadPyTorchSnapshot(stage);
        EXPECT_FALSE(data.empty()) << "Failed to load " << stage;
        LOG_INFO("[Parity] Loaded " << stage << ": " << data.size() << " elements");
    }

    // Try loading final stages
    auto final_norm = loadPyTorchSnapshot("FINAL_NORM");
    auto lm_head = loadPyTorchSnapshot("LM_HEAD");

    EXPECT_FALSE(final_norm.empty()) << "Failed to load FINAL_NORM";
    EXPECT_FALSE(lm_head.empty()) << "Failed to load LM_HEAD";

    // Expected: LM_HEAD = [batch=1, seq_len=9, vocab_size=151936] = 1367424 elements
    EXPECT_EQ(lm_head.size(), 1 * 9 * 151936) << "LM_HEAD snapshot size mismatch";

    LOG_INFO("[Parity] Successfully loaded FINAL_NORM: " << final_norm.size() << " elements");
    LOG_INFO("[Parity] Successfully loaded LM_HEAD: " << lm_head.size() << " elements");
}

/**
 * @brief Test: Incremental decode parity (autoregressive generation)
 *
 * This test compares Llaminar's incremental decode outputs against PyTorch's.
 * We run 5 decode steps after prefill and compare:
 *   - LM_HEAD logits (cosine similarity, KL divergence)
 *   - Top-1 and Top-5 token overlap
 *   - Layer 0 intermediate activations
 *
 * The test uses PyTorch's decode tokens (from metadata) to ensure fair comparison.
 * This is critical because any small numerical difference in prefill could cause
 * argmax divergence, and using different tokens would make comparison meaningless.
 *
 * Pass criteria (per decode step):
 *   - Cosine similarity >= 0.99 for LM_HEAD, OR
 *   - KL divergence < 0.15 for probability distributions
 *
 * Overall pass criteria:
 *   - At least 4 of 5 decode steps pass
 *   - Top-1 accuracy >= 80% (same predicted token)
 */
TEST_F(Qwen2FP32PrefillVsPytorch, IncrementalDecodeVsPytorch)
{
    // Check if decode snapshots exist
    auto decode_step0_lm_head = loadPyTorchSnapshot("decode_step0_LM_HEAD");
    if (decode_step0_lm_head.empty())
    {
        GTEST_SKIP() << "Decode snapshots not found. Run: python3 python/reference/generate_qwen2_pipeline_snapshots.py --decode-steps 3 --output " << snapshot_dir_;
    }

    // Read PyTorch's decode tokens from metadata
    // This is CRITICAL: We must use the SAME tokens PyTorch used for fair comparison
    // because prefill numerical differences cause argmax divergence
    std::vector<int> pytorch_decode_tokens = readDecodeTokensFromMetadata();
    if (pytorch_decode_tokens.empty())
    {
        GTEST_SKIP() << "No decode_tokens in metadata. Regenerate snapshots with: python3 python/reference/generate_qwen2_pipeline_snapshots.py --decode-steps 3 --output " << snapshot_dir_;
    }

    ASSERT_TRUE(setupPipeline());

    std::vector<int> tokens = readTokenIdsFromMetadata();
    ASSERT_FALSE(tokens.empty());

    int prefill_seq_len = static_cast<int>(tokens.size());

    LOG_INFO("[Parity] Testing incremental decode parity");
    LOG_INFO("[Parity] Prefill tokens: " << prefill_seq_len);
    LOG_INFO("[Parity] Using PyTorch decode tokens: " << pytorch_decode_tokens.size() << " tokens");

    // 1. Run prefill (to populate KV cache)
    bool success = runner_->forward(tokens.data(), tokens.size());
    ASSERT_TRUE(success) << "Prefill forward pass failed";

    size_t vocab_size = model_ctx_->model().vocab_size;

    // 2. Run decode steps using PyTorch's tokens and compare
    // Relaxed thresholds for decode steps (error accumulates through layers and steps)
    const float COSINE_THRESHOLD = 0.99f; // Slightly relaxed from 0.999 for decode
    const float KL_THRESHOLD = 0.15f;

    int decode_steps_passed = 0;
    int decode_steps_total = 0;
    int top1_matches = 0;
    std::vector<float> step_cosines;
    std::vector<float> step_kl_divs;

    // We want at least TEST_DECODE_STEPS decode steps (or however many are available)
    size_t num_decode_steps = std::min(pytorch_decode_tokens.size(), static_cast<size_t>(TEST_DECODE_STEPS));

    ASSERT_GE(pytorch_decode_tokens.size(), static_cast<size_t>(TEST_DECODE_STEPS))
        << "Not enough decode tokens from PyTorch metadata. Expected " << TEST_DECODE_STEPS
        << " but got " << pytorch_decode_tokens.size() << ". Regenerate snapshots with --decode-steps " << TEST_DECODE_STEPS;

    for (size_t step = 0; step < num_decode_steps; ++step)
    {
        std::string step_prefix = "decode_step" + std::to_string(step);

        // Check if this decode step snapshot exists
        auto pytorch_decode_lm_head = loadPyTorchSnapshot(step_prefix + "_LM_HEAD");
        if (pytorch_decode_lm_head.empty())
        {
            LOG_WARN("[Parity] " << step_prefix << "_LM_HEAD snapshot not found, stopping decode comparison");
            break;
        }
        decode_steps_total++;

        // Use PyTorch's decode token for this step (ensures fair comparison)
        int current_token = pytorch_decode_tokens[step];
        LOG_INFO("[Parity] Running decode step " << step << " with PyTorch token " << current_token);

        // Clear snapshots before decode step
        runner_->clearSnapshots();

        // Run single-token decode
        std::vector<int> decode_token = {current_token};
        success = runner_->forward(decode_token.data(), 1);
        ASSERT_TRUE(success) << "Decode step " << step << " failed";

        // Get Llaminar logits
        size_t decode_logits_size;
        const float *llaminar_decode_logits = runner_->getSnapshot("LM_HEAD", decode_logits_size);
        ASSERT_NE(llaminar_decode_logits, nullptr) << "Failed to get decode LM_HEAD snapshot";

        // Expected: [1, 1, vocab_size] = vocab_size elements
        EXPECT_EQ(decode_logits_size, vocab_size)
            << "Decode logits size mismatch: expected " << vocab_size << ", got " << decode_logits_size;
        EXPECT_EQ(pytorch_decode_lm_head.size(), vocab_size)
            << "PyTorch decode logits size mismatch: expected " << vocab_size << ", got " << pytorch_decode_lm_head.size();

        // Compare logits
        auto result = compareTensors(llaminar_decode_logits, pytorch_decode_lm_head, decode_logits_size);

        // Compute KL divergence for this decode step
        float kl_div = computeKLDivergence(
            llaminar_decode_logits, pytorch_decode_lm_head.data(),
            decode_logits_size, vocab_size);

        // Compute top-K overlap
        float top1_overlap = computeTopKOverlap(
            llaminar_decode_logits, pytorch_decode_lm_head.data(),
            decode_logits_size, vocab_size, 1);
        float top5_overlap = computeTopKOverlap(
            llaminar_decode_logits, pytorch_decode_lm_head.data(),
            decode_logits_size, vocab_size, 5);

        std::cout << "\n=== " << step_prefix << " LM_HEAD ===" << std::endl;
        std::cout << "  Cosine Sim:     " << std::fixed << std::setprecision(6) << result.cosine_similarity << std::endl;
        std::cout << "  KL Divergence:  " << std::fixed << std::setprecision(6) << kl_div << std::endl;
        std::cout << "  Top-1 Overlap:  " << std::fixed << std::setprecision(2) << (top1_overlap * 100.0f) << "%" << std::endl;
        std::cout << "  Top-5 Overlap:  " << std::fixed << std::setprecision(2) << (top5_overlap * 100.0f) << "%" << std::endl;
        std::cout << "  Max Abs Diff:   " << result.max_abs_diff << std::endl;

        // Get Llaminar's next token
        int llaminar_next_token = 0;
        float llaminar_max = llaminar_decode_logits[0];
        for (size_t i = 1; i < vocab_size; ++i)
        {
            if (llaminar_decode_logits[i] > llaminar_max)
            {
                llaminar_max = llaminar_decode_logits[i];
                llaminar_next_token = static_cast<int>(i);
            }
        }

        // Get PyTorch's next token
        int pytorch_next_token = 0;
        float pytorch_max = pytorch_decode_lm_head[0];
        for (size_t i = 1; i < vocab_size; ++i)
        {
            if (pytorch_decode_lm_head[i] > pytorch_max)
            {
                pytorch_max = pytorch_decode_lm_head[i];
                pytorch_next_token = static_cast<int>(i);
            }
        }

        // Track top-1 match
        bool token_match = (llaminar_next_token == pytorch_next_token);
        if (token_match)
        {
            top1_matches++;
        }

        std::cout << "  Llaminar next:  " << llaminar_next_token << std::endl;
        std::cout << "  PyTorch next:   " << pytorch_next_token << std::endl;
        std::cout << "  Token match:    " << (token_match ? "✓" : "✗") << std::endl;

        // Pass criteria: cosine similarity >= threshold OR KL divergence < threshold
        bool step_passed = (result.cosine_similarity >= COSINE_THRESHOLD) || (kl_div < KL_THRESHOLD);
        std::cout << "  Status:         " << (step_passed ? "✓ PASSED" : "✗ FAILED") << std::endl;

        // Track statistics
        step_cosines.push_back(result.cosine_similarity);
        step_kl_divs.push_back(kl_div);

        if (step_passed)
        {
            decode_steps_passed++;
        }

        // Also compare intermediate stages for layer 0 (detailed debugging)
        auto pytorch_layer0_attn_norm = loadPyTorchSnapshot(step_prefix + "_layer0_ATTENTION_NORM");
        if (!pytorch_layer0_attn_norm.empty())
        {
            size_t llaminar_size;
            const float *llaminar_data = runner_->getSnapshot("layer0_ATTENTION_NORM", llaminar_size);
            if (llaminar_data != nullptr)
            {
                auto attn_norm_result = compareTensors(llaminar_data, pytorch_layer0_attn_norm, llaminar_size);
                std::cout << "  layer0_ATTN_NORM cosine: " << std::fixed << std::setprecision(6)
                          << attn_norm_result.cosine_similarity << std::endl;
            }
        }
    }

    // Compute statistics
    float avg_cosine = 0.0f, min_cosine = 1.0f;
    float avg_kl = 0.0f, max_kl = 0.0f;
    for (size_t i = 0; i < step_cosines.size(); ++i)
    {
        avg_cosine += step_cosines[i];
        avg_kl += step_kl_divs[i];
        if (step_cosines[i] < min_cosine)
            min_cosine = step_cosines[i];
        if (step_kl_divs[i] > max_kl)
            max_kl = step_kl_divs[i];
    }
    if (!step_cosines.empty())
    {
        avg_cosine /= step_cosines.size();
        avg_kl /= step_kl_divs.size();
    }

    float top1_accuracy = decode_steps_total > 0 ? (100.0f * top1_matches / decode_steps_total) : 0.0f;

    // Summary
    std::cout << "\n╔══════════════════════════════════════════════════════════════╗" << std::endl;
    std::cout << "║           INCREMENTAL DECODE PARITY SUMMARY                  ║" << std::endl;
    std::cout << "╠══════════════════════════════════════════════════════════════╣" << std::endl;
    std::cout << "║  Decode steps tested:    " << std::setw(3) << decode_steps_total << "                                   ║" << std::endl;
    std::cout << "║  Decode steps passed:    " << std::setw(3) << decode_steps_passed
              << " / " << decode_steps_total << " ("
              << std::fixed << std::setprecision(0) << (decode_steps_total > 0 ? (100.0f * decode_steps_passed / decode_steps_total) : 0.0f)
              << "%)                         ║" << std::endl;
    std::cout << "╠══════════════════════════════════════════════════════════════╣" << std::endl;
    std::cout << "║  Cosine Similarity:                                          ║" << std::endl;
    std::cout << "║    Average:              " << std::fixed << std::setprecision(6) << avg_cosine << "                           ║" << std::endl;
    std::cout << "║    Minimum:              " << std::fixed << std::setprecision(6) << min_cosine << "                           ║" << std::endl;
    std::cout << "║  KL Divergence:                                              ║" << std::endl;
    std::cout << "║    Average:              " << std::fixed << std::setprecision(6) << avg_kl << "                           ║" << std::endl;
    std::cout << "║    Maximum:              " << std::fixed << std::setprecision(6) << max_kl << "                           ║" << std::endl;
    std::cout << "╠══════════════════════════════════════════════════════════════╣" << std::endl;
    std::cout << "║  Top-1 Token Match:      " << std::setw(3) << top1_matches << " / " << decode_steps_total
              << " (" << std::fixed << std::setprecision(0) << top1_accuracy << "%)                          ║" << std::endl;
    std::cout << "╚══════════════════════════════════════════════════════════════╝" << std::endl;

    // Assertions
    // At least 80% of decode steps should pass (cosine >= 0.99 or KL < 0.15)
    int min_steps_passed = static_cast<int>(decode_steps_total * 0.8);
    EXPECT_GE(decode_steps_passed, min_steps_passed)
        << "Not enough decode steps passed: " << decode_steps_passed << "/" << decode_steps_total
        << " (required: " << min_steps_passed << ")";

    // Top-1 accuracy should be >= 60% (token predictions should mostly match)
    EXPECT_GE(top1_accuracy, 60.0f)
        << "Top-1 token accuracy too low: " << top1_accuracy << "% (required: 60%)";

    // Average cosine similarity should be >= 0.99 (strong alignment)
    EXPECT_GE(avg_cosine, 0.99f)
        << "Average cosine similarity too low: " << avg_cosine << " (required: 0.99)";

    LOG_INFO("[Parity] Incremental decode parity test completed");
}

/**
 * @brief Test: Incremental decode consistency (internal validation)
 *
 * Validates that Qwen2Pipeline's incremental decode produces consistent,
 * non-degenerate outputs across multiple decode steps using Llaminar's own
 * argmax tokens (not PyTorch's).
 *
 * Key aspects tested:
 * - KV cache accumulation across decode steps
 * - Logits are well-formed (finite, reasonable range)
 * - Generated tokens are valid vocabulary indices
 * - Consecutive decode steps produce different outputs (not stuck in loop)
 * - Decode logits have reasonable entropy (not collapsed to single token)
 *
 * This is a complementary test to IncrementalDecodeVsPytorch:
 * - IncrementalDecodeVsPytorch: Uses PyTorch's tokens for fair comparison
 * - IncrementalDecodeConsistency: Uses Llaminar's tokens for end-to-end validation
 */
TEST_F(Qwen2FP32PrefillVsPytorch, IncrementalDecodeConsistency)
{
    ASSERT_TRUE(setupPipeline());

    std::vector<int> tokens = readTokenIdsFromMetadata();
    ASSERT_FALSE(tokens.empty());

    int prefill_seq_len = static_cast<int>(tokens.size());
    size_t vocab_size = model_ctx_->model().vocab_size;

    LOG_INFO("[Decode] Testing incremental decode consistency");
    LOG_INFO("[Decode] Prefill tokens: " << prefill_seq_len);

    // 1. Run prefill
    bool success = runner_->forward(tokens.data(), tokens.size());
    ASSERT_TRUE(success) << "Prefill forward pass failed";

    // Get argmax token from prefill logits
    size_t prefill_logits_size;
    const float *prefill_logits = runner_->getSnapshot("LM_HEAD", prefill_logits_size);
    ASSERT_NE(prefill_logits, nullptr) << "Failed to get prefill LM_HEAD snapshot";

    size_t last_token_offset = (prefill_seq_len - 1) * vocab_size;
    const float *last_token_logits = prefill_logits + last_token_offset;

    // Find argmax
    int first_decode_token = 0;
    float max_logit = last_token_logits[0];
    for (size_t i = 1; i < vocab_size; ++i)
    {
        if (last_token_logits[i] > max_logit)
        {
            max_logit = last_token_logits[i];
            first_decode_token = static_cast<int>(i);
        }
    }
    LOG_INFO("[Decode] First decode token (from prefill argmax): " << first_decode_token);

    // 2. Run decode steps and validate
    const int NUM_DECODE_STEPS = 5;
    int current_token = first_decode_token;

    std::vector<int> generated_tokens;
    std::vector<float> logit_entropies;
    int decode_steps_passed = 0;

    std::cout << "\n╔════════════════════════════════════════════════════════════╗" << std::endl;
    std::cout << "║              INCREMENTAL DECODE CONSISTENCY TEST            ║" << std::endl;
    std::cout << "╠════════════════════════════════════════════════════════════╣" << std::endl;

    for (int step = 0; step < NUM_DECODE_STEPS; ++step)
    {
        LOG_INFO("[Decode] Step " << step << " with token " << current_token);

        // Clear snapshots before decode step
        runner_->clearSnapshots();

        // Run single-token decode
        std::vector<int> decode_token = {current_token};
        success = runner_->forward(decode_token.data(), 1);
        ASSERT_TRUE(success) << "Decode step " << step << " failed";

        // Get logits
        size_t decode_logits_size;
        const float *decode_logits = runner_->getSnapshot("LM_HEAD", decode_logits_size);
        ASSERT_NE(decode_logits, nullptr) << "Failed to get decode LM_HEAD snapshot";

        // Validate logits size
        ASSERT_EQ(decode_logits_size, vocab_size)
            << "Decode logits size mismatch: expected " << vocab_size << ", got " << decode_logits_size;

        // Check 1: All logits are finite
        bool all_finite = true;
        float min_logit = decode_logits[0];
        float max_logit_val = decode_logits[0];

        for (size_t i = 0; i < vocab_size; ++i)
        {
            if (!std::isfinite(decode_logits[i]))
            {
                all_finite = false;
                break;
            }
            min_logit = std::min(min_logit, decode_logits[i]);
            max_logit_val = std::max(max_logit_val, decode_logits[i]);
        }
        EXPECT_TRUE(all_finite) << "Decode step " << step << " has non-finite logits";

        // Check 2: Logit range is reasonable (not exploded)
        float logit_range = max_logit_val - min_logit;
        EXPECT_LT(logit_range, 1000.0f) << "Logit range too large at step " << step << ": " << logit_range;
        EXPECT_GT(logit_range, 0.01f) << "Logit range too small at step " << step << ": " << logit_range;

        // Check 3: Compute entropy (diversity of distribution)
        // Softmax and entropy
        float max_for_softmax = max_logit_val;
        std::vector<float> probs(vocab_size);
        double sum_softmax = 0.0;
        for (size_t i = 0; i < vocab_size; ++i)
        {
            probs[i] = std::exp(decode_logits[i] - max_for_softmax);
            sum_softmax += probs[i];
        }

        double entropy = 0.0;
        for (size_t i = 0; i < vocab_size; ++i)
        {
            double p = probs[i] / sum_softmax;
            if (p > 1e-10)
            {
                entropy -= p * std::log(p);
            }
        }
        logit_entropies.push_back(static_cast<float>(entropy));

        // Check 4: Find argmax and validate it's a valid token
        int next_token = 0;
        float next_max = decode_logits[0];
        for (size_t i = 1; i < vocab_size; ++i)
        {
            if (decode_logits[i] > next_max)
            {
                next_max = decode_logits[i];
                next_token = static_cast<int>(i);
            }
        }

        EXPECT_GE(next_token, 0) << "Invalid token at step " << step;
        EXPECT_LT(static_cast<size_t>(next_token), vocab_size) << "Token out of vocabulary at step " << step;

        generated_tokens.push_back(next_token);

        // Check 5: Entropy should be reasonable (not degenerate)
        // Very low entropy means model is stuck on one token
        // Very high entropy means random noise
        // Typical LLM entropy is 1-8 nats
        bool entropy_ok = (entropy > 0.1 && entropy < 15.0);

        bool step_passed = all_finite && (logit_range < 1000.0f) && entropy_ok;
        if (step_passed)
            decode_steps_passed++;

        std::cout << "║  Step " << step << ": token=" << std::setw(6) << current_token
                  << " → next=" << std::setw(6) << next_token
                  << " | entropy=" << std::fixed << std::setprecision(2) << std::setw(5) << entropy
                  << " | range=" << std::setw(6) << std::setprecision(1) << logit_range
                  << " | " << (step_passed ? "✓" : "✗") << " ║" << std::endl;

        current_token = next_token;
    }

    // Check 6: Generated tokens should not all be the same (not stuck in loop)
    bool has_variety = false;
    if (generated_tokens.size() >= 2)
    {
        for (size_t i = 1; i < generated_tokens.size(); ++i)
        {
            if (generated_tokens[i] != generated_tokens[0])
            {
                has_variety = true;
                break;
            }
        }
    }

    std::cout << "╠════════════════════════════════════════════════════════════╣" << std::endl;
    std::cout << "║  Token variety: " << (has_variety ? "✓ Yes (not stuck)" : "⚠ No (possible loop)")
              << std::setw(has_variety ? 27 : 21) << " ║" << std::endl;
    std::cout << "║  Steps passed:  " << decode_steps_passed << "/" << NUM_DECODE_STEPS
              << std::setw(35) << " ║" << std::endl;
    std::cout << "╚════════════════════════════════════════════════════════════╝" << std::endl;

    // Print generated sequence
    std::cout << "\nGenerated token sequence: [";
    for (size_t i = 0; i < generated_tokens.size(); ++i)
    {
        if (i > 0)
            std::cout << ", ";
        std::cout << generated_tokens[i];
    }
    std::cout << "]" << std::endl;

    // Assertions
    EXPECT_EQ(decode_steps_passed, NUM_DECODE_STEPS) << "Not all decode steps passed validation";
    EXPECT_TRUE(has_variety) << "Model appears stuck generating same token";
}
